### ISSUE TITLE
records: allow users to update publication information

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#100]
This could be done automatically via a Celery task that runs over all records, say once a week, or by displaying a button on each record (only if a user has Coordinator privileges) allowing publication information to be updated for that record.  The publication information should also be updated for records that have an Inspire ID attached, but have not yet been finalised (the existing CLI command currently doesn't work for these cases).  The existing CLI command (e.g. `hepdata migrator update -i 'ins1498566' -ro True`) should not be reliant on hepdata.cedar.ac.uk in preparation for the old site being closed down.

**Comment by ghost** [comment]
Hi, I think this would be a very useful feature. An automated solution would mean less work for me, although I'd like to receive an email asking me for confirmation, or at least a notification about the update. At the moment, there's only one record that would need updating, perhaps you could look into this if you find the time: https://www.hepdata.net/record/76903
Thanks! Kilian

**Comment by alex-t-grecu** [comment]
Dear developers,
I hope this will help give higher priority to find a solution for this update of HepData record meta information from Inspirehep.net. From a coordinator's point of view the update should be manual and maybe restricted to coordinator role only (it is their responsibility after all). Further more it would be interesting to have an automatic method to detect when meta information changes in InspireHep.net such as when an erratum to a paper is published possibly affecting the data recorded in HepData (which might need an update) - and of course, send an e-mail to the coordinator. I think there are quite a bunch of HepData records which require updating meta information at the moment so I'm looking forward to the implementation of this feature in the web interface (also offering to act as guinea pig for its commissioning) and I hope my tiny input on this topic will prove helpful.
