### ISSUE TITLE
Downloaded YAML pack fails when re-uploaded

### ISSUE THREAD

**Issue by jmontejo** [HEPData/hepdata#101]
Hi,
I'm working on https://www.hepdata.net/record/77491 and I was doing the upload in the old hepdata format. Since I need to include files to the record I tried downloading the record in YAML and editing it to add the files.
It turns out that I can't upload the same .tar.gz even before modifying it, I get a server error.

I would have guessed that the same files I get when I download would be in a correct format to be uploaded again?

Cheers
Javier

**Comment by GraemeWatt** [comment]
Hi Javier.  Sorry, this is a known issue which I will fix in the next release of the [hepdata-converter](https://github.com/HEPData/hepdata-converter) package.  You need to remove the `hepdata_doi` and `table_doi` lines containing `!!python/unicode` tags from the `submission.yaml` file in a downloaded YAML submission.  I mentioned this to @krosbach in an email this afternoon and he said he would pass on the information (I will forward you the email).  In future please try asking the Coordinator for the record if they can resolve the problem, before raising the issue more widely.

**Comment by ghost** [comment]
Thanks Graeme for this fix and apologies for our internal miscommunication!
