### ISSUE TITLE
submission: update last_updated date when a record is uploaded or finalised

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#103]
The `last_updated` field of the `hepsubmission` table corresponds to the timestamp that a record was created, and it is currently not updated when a new upload is made, or when a record is finalised.  This means that the "Recently Updated Submissions" on the homepage is misleading, as it shows the three most recently *created* submissions, not the three most recent *finalised* submissions.

**Comment by ghost** [comment]
It would be good if this could be fixed soon, we're currently preparing multiple records in parallel and it's sometimes hard to keep track of changes. Knowing the time of the last update would simplify my administration task a lot.
