### ISSUE TITLE
Possible issue when downloading tables with multiple data columns in some formats (ROOT, CSV)

### ISSUE THREAD

**Issue by andreadotti** [HEPData/hepdata#119]
Hello, I am not able to download tables from an article: 
https://hepdata.net/record/ins790079
Note tables have multiple columns. I cannot download results in some of the formats: `ROOT`, `CSV`
Instead the formats `YAML` and `YODA` seem to work. This is the case either trying to download all tables at once, or table by table.

Please note that for other articles in which tables have a single columns (e.g. https://hepdata.net/record/ins325149) all formats work as expected. This difference got me thinking about the possible problem being the multiple columns.

For the cases in which it does **not** work, I get a timeout from web-server.

Regards,
Andrea Dotti

**Comment by GraemeWatt** [comment]
Thanks for the report, @andreadotti.  It seems that the Docker container running the converter software had died, so I've now restarted it.  Multiple columns are supported by the converter.  The conversions that worked might have been cached on the disk or perhaps the converter was still partially functional.  In any case, please let me know if you continue to experience problems.

Best regards,
Graeme Watt (Database Manager for HEPData)

**Comment by andreadotti** [comment]
Many thanks. It works as expected.
Andrea
