### ISSUE TITLE
10.17182/hepdata.45229 points to deleted INSPIRE record

### ISSUE THREAD

**Issue by kaplun** [HEPData/hepdata#124]
https://www.hepdata.net/record/45229 points to http://inspirehep.net/record/142029 which no longer exists because it got merged into: https://inspirehep.net/record/148976

Could the link be corrected on HEPData? This is currently the only case and would simplify (for the time being) some scripts on INSPIRE legacy that are linking back to HEPData.

**Comment by GraemeWatt** [comment]
OK, I've updated the `inspire_id` in the `hepsubmission` table of the database and in the JSON record.  Then I re-registered the record with DataCite so that http://dx.doi.org/10.17182/hepdata.45229 redirects to https://www.hepdata.net/record/ins148976.
