### ISSUE TITLE
Table sometimes doesn't load

### ISSUE THREAD

**Issue by ahinzmann** [HEPData/hepdata#129]
While reviewing this record:
https://www.hepdata.net/record/79857
it was recognized, that table 17 sometimes does not load. Clicking 10 times on the table, only in ~2 cases, the table and plot was displayed, otherwise it loaded endlessly. The table content is similar to all other tables, so this could be a feature of the webinterface or the record? Not clear.

**Comment by GraemeWatt** [comment]
Thanks for the report.  It seems that something went wrong during the original upload and some of the stored YAML data files on the disk are empty.  (Maybe the uploader saw a server error at the time.)  I found the last `oldhepdata` file that was uploaded on Tuesday at 13:36 (CET).  I uploaded again and now all tables can be loaded.  By the way, for problems specific to certain records, it's probably better just to send email to info@hepdata.net than to create a GitHub issue.
