### ISSUE TITLE
hepdata_records: leave more space between multiple lines of keywords

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#131]
For example, https://hepdata.net/record/ins84864 has a long list of reaction keywords which overlap if the browser window is small enough that the list wraps onto a second line.

The elements `.keyword-name` and `.keyword-value` in the file `record.less` should be modified to introduce more space between multiple lines.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#14
