### ISSUE TITLE
Log Scale (Y) not available if any entries are 0

### ISSUE THREAD

**Issue by jghaley** [HEPData/hepdata#131]
If any of the dependent values in a table are zero, the web interface does not allow to plot in log scale for the y-axis.  In such cases, it would be useful if Log Scale (Y) was still possible and just used the smallest non-zero value for the lower bound.  (Even better would be to have the ability to set min and max X, Y, and Z values for plots, but that is probably much more difficult to implement.)

**Comment by alisonrclarke** [comment]
@GraemeWatt Would it also be useful to do the same for Log Scale (X)?

**Comment by GraemeWatt** [comment]
It's less important, but it would be useful if you can work out how to do it.
