### ISSUE TITLE
search: ordering by "latest" does not work for multiple submissions on the same day

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#132]
If multiple submissions are made on the same day, the "Recently Updated Submissions" box on the homepage does not always show the last two, and similarly ordering by "latest" does not show the last submission at the top.  Ideally we would store the time of submission as well as the date of submission, so that ordering by "latest" would sort on the combined date+time.  A timestamp is stored for each record in the old HepData and we already export it as "dateupdated" in the YAML file as "dd/mm/yyyy hh:mm:ss".  If it is too much work to rewrite the code, an inferior solution would be to sort first by the date, then in reverse order by the new HEPData record number, so that the most recently added record would appear at the top of the "latest" search.  But storing the time with the date would be preferable.

**Comment by eamonnmag** [comment]
Fixed now.
