### ISSUE TITLE
hepdata_records: only display first ~10-100 rows by default for very large tables

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#133]
For very long tables (possibly thousands of lines or more) it would make sense to only display the first ~10-100 rows by default (with the rest of the table hidden) with an option to display more rows if the user requests.  In this case, the user is likely to be more interested in downloading the table in an accessible format (such as ROOT) than inspecting all rows of the table in a web browser.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#28
