### ISSUE TITLE
hepdata_records: choose appropriate number of decimal places to display errors

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#134]
Currently, all errors are displayed to two decimal places in the displayed tables.  This works most of the time, but, for example, http://hepdata.net/record/ins1370682 displays errors as 0.00, cf. the original http://hepdata.cedar.ac.uk/view/ins1370682 where the first error (0.000307) is displayed to the same number of decimal places as the central value, i.e. 0.0003.  A similar choice should be made in the new HEPData.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#17
