### ISSUE TITLE
plots: provide support for tables with zero independent variables and one or more dependent variables

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#135]
(This issue arose in the discussion of #97.)

Single-number measurements (for example, a total cross section) that are not a function of any "independent variable" are very common, but are not properly supported in either the old HepData or the new HEPData.  Usually, we artificially assign SQRT(S) as the independent variable, but it would be better to assign SQRT(S) as a qualifier and not have any independent variables.

For visualisation, you could create an artificial X axis (say, from 0 to 1) and just plot the data point in the middle (say, at 0.5), leaving the X axis unlabelled (and with no tick marks).

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#30
