### ISSUE TITLE
plots: provide support for tables with only independent variables and no dependent variables

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#136]
For example, for contour plots that present an exclusion limit in the mass plane of two hypothetical particles (http://hepdata.net/record/ins1380183?table=Table4 cf. original
http://hepdata.cedar.ac.uk/view/ins1380183/d4) it would be more natural to give the tables as two independent variables (and no dependent variables) rather than one independent variable and one dependent variable, since the two masses are independent and could easily be interchanged, i.e. what is plotted are the mass values for which a dependent variable is held fixed.  The disadvantage is that we would not be able to attach qualifiers to such tables, as qualifiers currently only apply to dependent variables.  The alternative solution would be to format this example with two independent variables and a dummy dependent variable, and that might be an easier solution.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#15
