### ISSUE TITLE
plots: plot a separate variable for each dependent variable regardless of qualifiers

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#137]
For example, in http://hepdata.net/record/ins1186740 there are six dependent variables, but all variables are plotted as one.  This is because there is no qualifier that uniquely identifies them all, only a combination of qualifiers.  But a simpler approach would just loop over each dependent variable, regardless of the qualifiers, and plot each variable separately.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#16
