### ISSUE TITLE
invenio: upgrade to latest packages and resolve arising incompatibilities

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#138]
Invenio v3.0.0rc1 and v1.0.0 of the component packages break the HEPData [build](https://travis-ci.org/HEPData/hepdata/builds/359479197).  I've just pinned the Invenio versions in the `requirements.txt` file to mirror the [hepdata.net](https://hepdata.net) production environment.  This is intended to be a temporary measure, and the incompatibilities should be investigated so that the Invenio versions can be upgraded.

**Comment by alisonrclarke** [comment]
Fixed by PR #328
