### ISSUE TITLE
records: delete unused files from the CephFS disk

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#139]
The CERN EOS disk used to store uploaded data files currently has a quota of 5 TB storage space and 2 million files.  Check the quota with `eos root://eospublic.cern.ch quota /eos/hepdata` on any of the `hepdata-*` machines.  We recently needed to get the quota on the number of files extended from the original limit of 1 million files.  All uploads are currently retained on the disk and files are never deleted, even where they will never be used again.  For example, deleting a (Sandbox) record removes the record from the database, but files are retained on the disk.  Files corresponding to multiple uploads in preparation of a record are retained on the disk, but only the last upload will be accessible when a record is finalised.  A clean-up should be made to remove unused files from the disk as follows:

* [x] Delete directories from `/opt/hepdata/var/data/` that don't match a record in the current database.
* [x] Delete orphaned entries in the `dataresource` table
* [x] For finalised (and Sandbox) records, also delete directories corresponding to non-final uploads.
* [x] Modify the code to delete directories from `/opt/hepdata/var/data/` when a (Sandbox) record is deleted.
* [x] When a new upload of a record is made successfully, delete directories corresponding to previous uploads.
* ~~If a finalised record is deleted (which should be very rare), need to mark the corresponding metadata as "inactive" in DataCite and update the URL to https://www.hepdata.net/record/invalid_doi .~~ (See #233)

Obviously, any code performing this clean-up should be very thoroughly tested in order not to delete any valid data files!

**Comment by alisonrclarke** [comment]
As well as files being left on disk, there are some entries in the `dataresource` table which are not deleted when the associated `datasubmission` entry is deleted.

Working to fix this on the [fix/cephfs-directory-structure](/HEPData/hepdata/tree/fix/cephfs-directory-structure) branch, alongside #218.

**Comment by alisonrclarke** [comment]
Work still to do:

* [x] Add tests to increase coverage of `data_files.py`
* [x] Ensure handling of cascading deletes is consistent: I made changes to `submission/models.py` before realising that similar work is done in `cleanup_submission` in `records/utils/submission.py`.
