### ISSUE TITLE
migration: use "dateupdated" in the YAML export from the old HepData

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#139]
I just noticed that the "dateupdated" written in the YAML format exported from the old HepData is not imported as the "Last updated" date on hepdata.net, which is needed for the  "Recently Updated Submissions" box on the homepage and when sorting by "latest".  Instead the `submission.py` file assigns only the *first* date mentioned in the "modifications" (or today's date if invalid).  But the "modifications" are usually entered manually and are often missing or unreliable, whereas the "dateupdated" is an automatic timestamp and should be more reliable (at least for more recent records).  For example:

- http://hepdata.cedar.ac.uk/view/ins1384119/yaml has missing date in the "modifications" but a valid "dateupdated".
- http://hepdata.cedar.ac.uk/view/ins1388178/yaml has an earlier date in the "modifications" than the actual "dateupdated".
- http://hepdata.cedar.ac.uk/view/ins1203852/yaml was updated with another entry in the "modifications" but only the first entry is used in the `submission.py` file.

So the migration code needs to store the "dateupdated" in the YAML format and use it when sorting by "latest".  For new records, the "dateupdated" can be generated automatically when a record is finalised.  The time should be stored as well as the date (see #132).

**Comment by eamonnmag** [comment]
It does this. Although, it's possible, that I'm overriding that value whenever the submission is finalised. So good catch!

**Comment by GraemeWatt** [comment]
No, it looks like you don't parse `dateupdated` from the original YAML at all, only the first `date` stored as `modifications` which is generally less reliable:
https://github.com/HEPData/hepdata/blob/master/hepdata/modules/utils/submission.py#L208

**Comment by eamonnmag** [comment]
I never saw this dateupdated field in other outputs. Will modify for this.

**Comment by eamonnmag** [comment]
Done in new version.
![screen shot 2016-01-13 at 10 42 32](https://cloud.githubusercontent.com/assets/282396/12290751/c44c79c8-b9e3-11e5-9cd0-9e85c118e397.png)
