### ISSUE TITLE
accounts: Add ORCID mapping for accounts

### ISSUE THREAD

**Issue by jstypka** [HEPData/hepdata#14]
Current roles are mapped to local accounts, we need to investigate how it works with ORCID

**Comment by kaplun** [comment]
This should be transparently handled by Invenio. There is the concept of user in the system, and this is independent from how the user authenticated. In the user object you should be able on the other hand to retrieve the ORCID information.

@jmartinm do you have some pointers from Labs where you actually read user info from ORCID?

If you want to link a role to a user at runtime, you need to know which user it is. Normally you can search by email, or if you want to search by ORCID you can pass from the `userEXT` table.
