### ISSUE TITLE
migration: copy individual files linked from parent files to resource area on hepdata.net

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#141]
Clicking "Link to the SLHA files" in the Additional Resources for https://hepdata.net/record/ins1127601 gives links to individual .slha files stored on hepdata.cedar.ac.uk rather than hepdata.net.  I guess we should eventually copy these files across, i.e. everything in the web directory http://hepdata.cedar.ac.uk/resource/9719717 and replace hard-coded links to files in that directory.  Similarly for other records where files are linked from something like "insert.html" or "index.shtml".

**Comment by eamonnmag** [comment]
I'm not sure what to do here. In some respects, it may be better to list all resources directly in the YAML export as opposed to just this link. Having to support this page as an index, and convert all the HTML files to use correct links etc. is not going to be nice, but I'll give it a try. Now, this shows. But each of the Y links is still going back to cedar.hepdata. So, I need to pull the contents of these resource directories and create HEPData resource objects for them (in the db). Then, I need to go through the HTML files and replace all cedar.hepdata... links with hepdata/resource/<resource_id> links. 

![screen shot 2016-01-13 at 14 05 09](https://cloud.githubusercontent.com/assets/282396/12295104/20a6a1ce-b9ff-11e5-8e9c-641cfd34972c.png)

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#27
