### ISSUE TITLE
search: some records give "0 data tables" when data tables exist

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#141]
For example, a blank search (https://hepdata.net/search/?q=) currently gives 4 records out of 25 on the first page with "0 data tables".

**Comment by GraemeWatt** [comment]
I haven't seen this problem recently, so I'm closing it for now.

**Comment by GraemeWatt** [comment]
Reopening this issue as it still seems to be a problem.  Currently 10 out of the 25 records shown on the first page of https://hepdata.net/search/?q= have "0 data tables" when data tables exist.  For example, the first record https://www.hepdata.net/record/ins1857811 has 8 data tables, which appear correctly for search queries like https://www.hepdata.net/search/?q=CMS-HIG-20-017 or https://www.hepdata.net/search/?q=&collaboration=CMS but not for an empty search query.  Any comments, @alisonrclarke?

**Comment by alisonrclarke** [comment]
I think this could be a pagination/search size limit issue. The number of data tables comes from the elasticsearch results. We search publications and data tables separately, then combine the results.

The data search [has a limit of 50 times the size of publications requested](https://github.com/HEPData/hepdata/blob/15bdfe6f413fbee32ee5ee3373017764f9a0caf5/hepdata/ext/elasticsearch/api.py#L145), which I guess would usually be sufficient to ensure all data tables were returned for the given publications (and works when the search is more refined), but as there are currently some records with 65 or more data tables on the first page of search results, I guess that not all the data tables are being returned.

It might be worth increasing that limit to 100 as a first pass at fixing the issue.

**Comment by GraemeWatt** [comment]
Thanks!  I see the problem on my local instance and indeed changing the limit from `size*50` to `size*100` fixes it!

**Comment by alisonrclarke** [comment]
There might be a smarter way to do the search, e.g. for empty search queries we could just search for data tables relating to the publications already found, so it might be worth leaving this issue open even after changing the size limit.

**Comment by alisonrclarke** [comment]
> There might be a smarter way to do the search, e.g. for empty search queries we could just search for data tables relating to the publications already found, so it might be worth leaving this issue open even after changing the size limit.

Ignore that comment - we're already filtering on parent publication!
