### ISSUE TITLE
hepdata_records: display links to individual tables

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#142]
It's a nice feature that adding e.g. "?table=Table6" to the URL of a given record will go directly to that table.  But it's difficult for users to know that they can do this.  Ideally the URL would be updated with e.g. "?table=Table6" when a user clicks on the table name.  Alternatively a link could be given on the web page saying something like "Link to this table" that a user can copy and email to collaborators.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#21
