### ISSUE TITLE
search: allow searching by a particular field in the search box

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#143]
It seems that the search box does not allow searching by a particular field, e.g. "collaboration=ATLAS", which can only be done by clicking keywords in the left panel or by entering a search command directly in the URL.  The search box executes only a general query "q=ATLAS" which will search the paper title/abstract and table captions etc.  Similarly, if a user wants to search for a particular observable and/or reaction from the search box (like in the old HepData), it does not seem to be possible at the moment.  The search box should support more specific queries restricting to a particular field or combination of fields, i.e. it should have the same functionality as entering search commands directly in the URL, and the syntax should be documented.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#26
