### ISSUE TITLE
schema.org: encode metadata using JSON-LD instead of Microdata

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#145]
[Schema.org](https://schema.org) metadata is currently encoded in HEPData web pages using [Microdata](https://en.wikipedia.org/wiki/Microdata_(HTML)) (implemented by @eamonnmag).  This metadata is indexed for use in the new [Google Dataset Search](https://toolbox.google.com/datasetsearch) released today.  See blog articles from [Google AI](https://www.blog.google/products/search/making-it-easier-discover-datasets/) and [DataCite](https://doi.org/10.5438/5aep-2n86).

[JSON-LD](https://en.wikipedia.org/wiki/JSON-LD) is [emerging](https://doi.org/10.5281/zenodo.1202173) as the community standard and is the preferred format for Schema.org metadata by both Google and DataCite.  We should therefore encode [Schema.org](https://schema.org) metadata using JSON-LD instead of Microdata.  We should also check that the implementation follows Google's [guidelines for dataset providers](https://developers.google.com/search/docs/data-types/dataset).

Cc:  @mfenner @suenjedt

**Comment by mfenner** [comment]
@GraemeWatt happy to help with the JSON-LD.

**Comment by suenjedt** [comment]
Yes, as discussed earlier same here, happy to collaborate on this. cc @artemislav. Back then Eamonn had discussed this with Google btw. Happy to forward the correspondance.

**Comment by alisonrclarke** [comment]
See #162: plan is to use json-ld from datacite.
