### ISSUE TITLE
main page: print out timestamp when site was last deployed

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#146]
Can we print out somewhere on the hepdata.net main page a discrete timestamp when the site was last deployed?  (That makes it easier for developers to see which changes to the GitHub code are not yet deployed.)

**Comment by eamonnmag** [comment]
Added version to the home page. This should be updated on every release so that we know what is shown. It's VERRRY subtle :)

![screen shot 2016-02-11 at 14 11 07](https://cloud.githubusercontent.com/assets/282396/12977429/eb409e8a-d0ca-11e5-8446-0a5f0423282a.png)
