### ISSUE TITLE
inspire_datasource: allow automatic updating of publication information

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#147]
HEPData records will typically be submitted before the corresponding paper is published in a journal and so the Inspire record will not have the DOI and journal reference at the time of HEPData submission.  It would be nice if a script could be run periodically to pull the latest metadata from Inspire (such as publication information) and update the HEPData record automatically.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#20
