### ISSUE TITLE
DOIs: allow a DOI to be minted *before* a HEPData record has been finalised?

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#149]
I'm not sure how the DOI minting will work, but it would be good to allow a DOI to be minted *before* an Inspire ID has been attached to a HEPData record, i.e. assign a DOI at the same time that a new submission is created.  That way people can cite the DOI for the data in the publication associated with the data, then the first data citation will be generated when the publication appears on Inspire.  (It is a common request from authors that they want to refer to a persistent URL/DOI for the data in the associated publication.)

**Comment by eamonnmag** [comment]
This is a chicken and egg problem. Semantically, this would be the wrong thing to do since the point of DOIs is that the underlying content they represent should not change. It should be stable. So you need information about the publication already present to mint the DOI before creating it. Although, I obviously see your point.

**Comment by kaplun** [comment]
@eamonnmag this however happens already for publications. Big publishers are already minting DOIs even before papers are peer-reviewed and are only in draft. The DOI should point to a digital object but it doesn't necessary mean it won't evolve (e.g. this is important for SCOAP³, to know in advance DOI for statistic reasons).

In particular from: https://www.doi.org/faq.html
> [...]
> 7. If I have assigned a DOI name and I make a change to my material, should I assign a new DOI?

> The IDF does not have any rules on this. Individual RAs adopt appropriate rules for their community and application. As a general rule, if the change is substantial and/or it is necessary to identify both the original and the changed material, assign a new DOI name.
> [...]

**Comment by eamonnmag** [comment]
For me this is against the way DOIs were intended to be used. But, I don't really care if the rest of the community don't care either :)

**Comment by GraemeWatt** [comment]
I'm not sure of the exact technical steps involved in "minting" a DOI.  But from personal experience with journal publication (e.g. in JHEP) the DOI can be assigned before the final full-text is available (e.g. during the proof stage), but the DOI may not be resolved (e.g. at http://dx.doi.org) until a few days after the journal article appears online.  So we could internally allocate a DOI name based on the HEPData record number (e.g. `12.1234/HEPData.12345` would resolve to http://hepdata.net/record/12345) when a new submission is created, but we would not register the DOI until the HEPData record is finalised (after the Inspire ID is known).  That way people could cite the DOI for the data in the first arXiv version of the associated publication, although the DOI would not be resolved until the HEPData record is finalised and the DOI is registered.  However, this means we would need to ensure that the HEPData record numbers are persistent, which might not be the case.  The alternative option would be to only allocate DOI names based on the Inspire ID after a HEPData record is finalised (e.g. `12.1234/HEPData.ins1234567` would resolve to http://hepdata.net/record/ins1234567).  However, this means that the DOI for the HEPData record could not be cited in the first arXiv version of the corresponding publication.  I guess we can't have two DOIs, one based on the HEPData record number and one based on the Inspire ID, that both resolve to the same HEPData record (?).

**Comment by salmele** [comment]
>So we could internally allocate a DOI name based on the HEPData record number (e.g. 12.1234/HEPData.12345 would resolve to http://hepdata.net/record/12345) when a new submission is created, but we would not register the DOI until the HEPData record is finalised (after the Inspire ID is known). That way people could cite the DOI for the data in the first arXiv version of the associated publication, although the DOI would not be resolved until the HEPData record is finalised and the DOI is registered. 

An elegant solution (inspired by e.g. the https://figshare.com/blog/The_future_of_figshare/166 Figshare Embargoed files which "can still be cited as any other figshare article") would be to (1) register the DOI anyhow otherwise any linked reference 12.1234/HEPData.12345  in an arXiv paper will be broken and not used by author/usable by reader and (2) have a splash page to describe the fact that the record is being updated/curated/manipulated and from that page maybe then refer to something else (e.g. publishers/INSPIRE or something) so that in the meanwhile you do not create a dead end.

>However, this means we would need to ensure that the HEPData record numbers are persistent, which might not be the case. 

But, if HEPData mints DOI, this (or something similar) better be,

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#18
