### ISSUE TITLE
submission: allow automatic tweets to be sent when a record is finalised

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#150]
It would be nice to have an option in the submission system to send an automatic tweet using a Twitter API each time a record is finalised.  (Currently I'm just doing it manually.)  The tweets could have a standard format like 'Added [experiment] data on "[truncated paper title...]" to [URL]' where the paper title is truncated so that the tweet fits into 140 characters.

**Comment by eamonnmag** [comment]
Done in current new version of HEPData. How should we format the text? Obviously the latex is a problem.
<img width="590" alt="screen shot 2016-01-12 at 16 35 24" src="https://cloud.githubusercontent.com/assets/282396/12267888/8b9dc9cc-b94a-11e5-837f-21abab0f7b10.png">

**Comment by GraemeWatt** [comment]
Nice!  You can remove the LaTeX `$` symbols in the paper title and please write the paper title inside double-quote marks `"`.  A more advanced option would convert LaTeX symbols to Unicode, e.g. https://github.com/svenkreiss/unicodeit.  Currently I use http://www.unicodeit.net/ but some manual edits are needed, e.g. `\sqrt{s}` leaves the curly brackets so I need to write `\sqrts`.  Use `@ATLASpapers`, `@CMSpapers`, `@LHCbPhysics` or `@ALICEexperiment` for the four main LHC experiments or just the experiment name otherwise.  Maybe better to capitalise the hashtag as `#HEPData`.

**Comment by eamonnmag** [comment]
Found this, https://pypi.python.org/pypi/unicode_tex/0.1.1 will give it a try :)

**Comment by eamonnmag** [comment]
Could probably be improved a little, but it's not bad :+1: 
<img width="595" alt="screen shot 2016-01-12 at 20 15 38" src="https://cloud.githubusercontent.com/assets/282396/12274054/5716790a-b969-11e5-8a5f-f55e1d4d60cd.png">
