### ISSUE TITLE
hepdata_records: allow visualisation of .slha files using "slhaplot" script

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#151]
There is a package called [PySLHA](https://pypi.python.org/pypi/pyslha/) that contains a Python script called "slhaplot" to generate the mass spectrum from a .slha file: see Figure 1 of http://arxiv.org/abs/1305.4194 .  It would be nice to allow automatic visualisation of .slha files attached as Additional Resources, although this might introduce a LaTeX dependence.  This is a low priority, however.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#29
