### ISSUE TITLE
hepdata_records: preserve line breaks in the paper comments and table captions from the original YAML files

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#152]
Otherwise, e.g. the data abstract in https://hepdata.net/record/ins1203852 is much less readable than the original http://hepdata.cedar.ac.uk/view/ins1203852 .  I guess we just need to replace `\n` with `<br/>` in the HTML output.

Also, in converting the original single-file YAML format to the multiple-file YAML format, a lot of additional line breaks seem to be inserted.  This is probably because the `yaml.dump()` writer command wraps long lines of text by default and an argument `width` should be passed to preserve the original line breaks without wrapping long lines.

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#13
