### ISSUE TITLE
submission: allow direct upload of the single-file YAML format

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#153]
It would be nice to be able to directly upload the single-file YAML that we export from the old HepData, i.e. the hepdata-converter would need to be extended to convert the single-file YAML format to multi-file YAML format (HEPData/hepdata-converter#12) .  Since this is done anyway for the migration, could the code be integrated into the hepdata-converter?

**Comment by eamonnmag** [comment]
This issue was moved to HEPData/hepdata3#31
