### ISSUE TITLE
tests: increase Python test coverage

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#154]
Python test coverage is currently 68%: this could be improved.

**Comment by alisonrclarke** [comment]
Whilst we've made good progress on increasing coverage (now at nearly 90%), currently all `views.py` files are excluded from coverage checks. There is a lot of logic in `views.py` files and I think we should re-add them to the coverage checks. I'd suggest we just add them, accept that our coverage will drop, then try to ensure changes to `views.py` files are covered and that coverage increases with every change: now that our end to end tests are working it's easier to test these files than it was when they were excluded from coverage.

**Comment by alisonrclarke** [comment]
I've made some changes on the `coverage` branch to remove files from .coveragerc that I think we should be checking. [Latest results on coveralls](https://coveralls.io/builds/46566088) gives coverage of ~81%: so quite a drop but still respectable I think?

It might be worth going through those coverage results to see if there's anything else we think we should exclude?

**Comment by GraemeWatt** [comment]
I agree that we should include as much code as possible in the coverage, unless it is difficult or not meaningful to write a suitable test.  The `views.py` files were probably excluded originally because it is difficult to write unit tests, but the end-to-end tests make it easier to test the different endpoints.
