### ISSUE TITLE
submission: allow a "superadmin" to toggle privileges on and off

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#154]
Testing the submission system is a bit difficult because I have "superadmin" privileges.  It would be nice if a "superadmin" could temporarily switch off their privileges (and then later switch them back on again) so that I could see the system as viewed by a typical Coordinator/Uploader/Reviewer (in turn), e.g. for each of the roles at https://hepdata.net/admin/useraccrole/ there could be a column that says "Active" and a "superadmin" could toggle the role on or off without removing it completely.

**Comment by eamonnmag** [comment]
This is now gone in the new invenio, so it's not possible to do it. But, you can create any number of accounts now (for testing etc.) as long as the email is unique. There is no longer a tie to ORCID.
