### ISSUE TITLE
global: make code compatible with Python 3

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#158]
The codebase is largely written in Python 2 and should be made compatible for Python 3, given that Python 2 will not be maintained beyond 1st January 2020.  See https://docs.python.org/3/howto/pyporting.html for basic steps.

**Comment by alisonrclarke** [comment]
Working on this on [DurhamARC/hepdata](/DurhamARC/hepdata/tree/update/python3-compatibility).

Still need to:
- [x] Update other HEPData PIP modules and docker hub images:
    - [x] hepdata-validator
    - [x] hepdata-converter-docker
    - [x] hepdata-converter
    - [x] hepdata-converter-ws-docker
    - [x] hepdata-converter-ws
    - [x] hepdata-converter-ws-client
- [x] Get app and tests working on local server
- [x] Get tests working on Travis
- [x] Look at string -> bytes changes to ensure they're consistent
- [x] Check whether we can remove futurize as we'll probably be migrating straight to python3 servers

**Comment by alisonrclarke** [comment]
Tests are now all passing on my local machine, using locally-built docker images and pip packages. App seems to work too, apart from the converter.

**Comment by alisonrclarke** [comment]
Tests are now all passing on my local machine, using locally-built docker images and pip packages. App seems to work too, apart from the converter.

**Comment by alisonrclarke** [comment]
Tests are now all passing on my local machine, using locally-built docker images and pip packages. App seems to work too, apart from the converter.

**Comment by GraemeWatt** [comment]
All done!  Congratulations, @alisonrclarke!
