### ISSUE TITLE
submission: enter full Inspire URL or just the integer Inspire ID?

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#159]
I tried a test submission on my laptop where I clicked "Submit" and entered "http://inspirehep.net/record/1203852", i.e. the example.  This works to import the metadata and create the record, but then the Inspire Record in the search results links to "http://inspirehep.net/record/http://inspirehep.net/record/1203852" and the record links to "localhost:4000/record/inshttp://inspirehep.net/record/1203852".  So probably it's easiest just to support the Inspire ID itself (e.g. 1203852) on the "Submit" page.  Otherwise, if you also want to allow the full URL (e.g. http://inspirehep.net/record/1203852) when creating a new submission then you need to be consistent with using the Inspire ID in links.

**Comment by eamonnmag** [comment]
Submission system is completely different now. Only takes the ID.

![new-submission-form](https://cloud.githubusercontent.com/assets/282396/12274336/bea109ea-b96a-11e5-946f-de0e942dd5a9.gif)
