### ISSUE TITLE
docker: resurrect Docker build of main web application

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#159]
A working Docker installation might make it easier for new developers to start contributing to the software.  The [hepdata-docker](https://github.com/HEPData/hepdata-docker) repository should be resurrected.

**Comment by GraemeWatt** [comment]
Today we decided to move HEPData deployment from Puppet to Kubernetes.  A Docker build of the web application is therefore an essential requirement.

**Comment by alisonrclarke** [comment]
Is this complete now? (See also PR #211 for docker-compose.)

**Comment by GraemeWatt** [comment]
Yes, it was resolved by #193, so closing now.  I've just archived the old [hepdata-docker](https://github.com/HEPData/hepdata-docker) repository, but maybe it should be deleted to avoid confusion as it is no longer needed.
