### ISSUE TITLE
records: mint DOIs for local resource files attached to publication

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#162]
Local resource files (excluding links) specified in the first YAML document of the `submission.yaml` file should be allocated DOIs like `10.17182/hepdata.89408.v1/r1`, `10.17182/hepdata.89408.v1/r2`, `10.17182/hepdata.89408.v1/r3`, etc.  It will require a slight extension of the database model to add a `doi` field to the `dataresource` table.  A DataCite XML metadata template for resource files should be created analogous to [`datacite_data_record.xml`](https://raw.githubusercontent.com/HEPData/hepdata/master/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_data_record.xml) for data tables.

To start with, I've minted a DOI [10.17182/hepdata.89408.v1/r2](https://doi.org/10.17182/hepdata.89408.v1/r2) for [HEPData_workspaces.tar.gz](https://www.hepdata.net/record/resource/997020?view=true) attached to https://www.hepdata.net/record/ins1748602?version=1 by downloading the DataCite XML for the first table, making some manual edits (and correcting some typos), and uploading the new DataCite XML metadata to [DataCite Fabrica](https://doi.datacite.org/).  The DOI is now searchable from [DataCite Search](https://search.datacite.org/works/10.17182/hepdata.89408.v1/r2).

It would be better for the DOI to redirect to a landing page for the resource file rather than directly to the resource file itself.  However, it might still be useful to have an option to return the resource file directly from the DOI, probably using content negotiation.  The DOI should be clearly displayed on the landing page for the resource file, in the "Resources" widget, and in the "Citing this record" widget.

After code is successfully implemented to mint DOIs for local resource files of new submissions, it will be necessary to write a [CLI](https://github.com/HEPData/hepdata/blob/master/hepdata/cli.py) function to loop over all current submissions and mint DOIs for their local resource files.

Cc: @lukasheinrich

**Comment by GraemeWatt** [comment]
Following a request from @lukasheinrich, I've repeated the manual procedure described above to mint a DOI [10.17182/hepdata.90607.v3/r3](https://doi.org/10.17182/hepdata.90607.v3/r3) for [1Lbb-likelihoods-hepdata.tar.gz](https://hepdata.net/record/resource/1408476?view=true) attached to https://www.hepdata.net/record/ins1755298?version=3 and the DOI is again searchable from [DataCite Search](https://search.datacite.org/works/10.17182/hepdata.90607.v3/r3).

**Comment by GraemeWatt** [comment]
When addressing this issue, it would be good if a Schema.org [`contentURL`](https://schema.org/contentUrl) could be embedded on the landing page in JSON-LD format to make it machine-readable (see discussion in scikit-hep/pyhf#1491).  There's another open issue #145 to move from Schema.org Microdata to JSON-LD metadata for other HEPData web pages, so it might make sense to address that issue first.

**Comment by alisonrclarke** [comment]
Just starting to look into this. Do you think we need to differentiate between resources belonging to tables and those belonging to the submission (e.g. in the DOI format and the related identifiers) or can we just treat them all the same?

**Comment by GraemeWatt** [comment]
I didn't anticipate minting DOIs for additional resources attached to data tables, e.g. image files.  I think the extra DOIs are only needed for resources attached to the whole submission, i.e. validated by `additional_info_schema.json`.

**Comment by alisonrclarke** [comment]
> It would be better for the DOI to redirect to a landing page for the resource file rather than directly to the resource file itself. However, it might still be useful to have an option to return the resource file directly from the DOI, probably using content negotiation.

Under what circumstances would we want to return the resource file rather than the landing page? Are you thinking e.g. if the `user-agent` is not a browser, or using the `accept` header? I guess I'm trying to understand who would be trying to get to the file directly from the DOI and what they would be doing.

**Comment by GraemeWatt** [comment]
That was my misunderstanding of what's meant by content negotiation (it refers to DOI metadata in different formats, not the actual content), later clarified in [another comment](https://github.com/scikit-hep/pyhf/issues/1491#issue-922510252).  So we should always just return the landing page.

**Comment by alisonrclarke** [comment]
Breaking this down into a TODO list:

- [x] Add a landing page for resources
- [x] Mint DOIs for resources (pointing to landing page)
- [x] Add DOIs to resources widget
- [x] Add resource DOIs to 'Cite...' widget
- [x] Address #145 (ensuring `contentURL` is embedded on landing page) - see [comment](https://github.com/HEPData/hepdata/issues/162#issuecomment-943412364)
  - [x] Update DataCite XML to remove line breaks in generated JSON-LD
  - [x] Update DataCite XML so that JSON-LD contains as much info as possible
  - [x] Add DataDownload to JSON-LD
  - [x] Add JSON-LD to main homepage
  - [x] Add no index for QA site
- [x] Add content negotiation to DOI landing pages to return the file given an appropriate `Accept` header
- [x] Add CLI command to add resource DOIs for current submissions and update DataCite metadata for other DOIs
- [x] ~Check that DOIs are minted for resources added via the web interface rather than the original upload~ (only URLs can be added via web interface)
- [x] Add curl command for direct download from DOI
- [x] Address #415

**Comment by alisonrclarke** [comment]
Working on [resource-dois branch](/HEPData/hepdata/tree/resource-dois).

**Comment by GraemeWatt** [comment]
This article might be useful when implementing machine-readable metadata on the landing page:  https://doi.org/10.1038/s41597-019-0031-8

In particular, for the pyhf use case, it would be nice to add support for content negotiation, so that something like `curl -LH "Accept: application/ld+json" https://doi.org/10.17182/hepdata.89408.v1/r2` would directly return the Schema.org JSON-LD metadata including `contentURL`.  **Update**: that `curl` example doesn't work, since it uses [DataCite Content Negotiation](https://support.datacite.org/docs/datacite-content-resolver) to return DataCite JSON-LD metadata which doesn't contain `contentURL`.

Maybe we can use content negotiation to return the content directly.  The [DataCite Content Negotiation](https://support.datacite.org/docs/datacite-content-resolver) docs say "All requests for unknown content types will then be forwarded to the URL registered for the DOI in the handle system".  We could infer the MIME type of the resource file using [`mimetypes.guess_type`](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type).  The client (e.g. the pyhf code) could make a request like `requests.get(doi, headers=headers)` where `doi = 'https://doi.org/10.17182/hepdata.89408.v1/r2'` and `headers={'Accept': 'application/x-tar'}`.  The HEPData server would check whether the `Accept` type matches the resource file type and if so return the resource file itself.  Would this be possible, @alisonrclarke?

**Update**: I think we might be able to add media type/URL pairs to a DOI (https://support.datacite.org/reference/media), which might automatically allow content negotiation (see example at https://datacite.readthedocs.io).  I'll write to DataCite support to clarify.  For the Schema.org JSON-LD metadata on the landing page, there's a link to a [Javascript snippet](https://gist.github.com/kjgarza/34ca6a866b4437bc1c07d84f208a01c4) from "[How do I expose my datasets to Google Dataset Search?](https://support.datacite.org/docs/how-do-i-expose-my-datasets-to-google-dataset-search)" which gets the metadata in Schema.org JSON-LD format from DataCite.  This would be more efficient than having separate metadata duplicated in the landing page and in the DataCite XML template.  We should set `resourceTypeGeneral` to `Dataset` rather than `Other` so that the resource files will be automatically indexed by [Google Dataset Search](https://toolbox.google.com/datasetsearch).  We probably need to [block search indexing with `noindex`](https://developers.google.com/search/docs/advanced/crawling/block-indexing) on the QA site since I see that QA records currently appear in search results.

**Comment by alisonrclarke** [comment]
> We should set `resourceTypeGeneral` to `Dataset` rather than `Other` so that the resource files will be automatically indexed by Google Dataset Search. 

[Google's dataset docs](https://developers.google.com/search/docs/advanced/structured-data/dataset) gives examples of what qualifies as a dataset, and I'm not sure that all resource types fit the definition (e.g. python scripts, pdfs). I'm not sure whether Google would class HEPData as lower quality if we try to add things that aren't datasets.

Options are probably:

1. Set all resources as `Dataset` (and risk decreasing SEO)
2. Set all resources as `Other` (and miss out some data files from Google Data Search)
3. Try to detect whether it's a dataset from the file extension (which may be inaccurate, e.g. we won't know what is inside tar files, and it may be hard to include all data types).

**Comment by GraemeWatt** [comment]
Yes, I had some doubts about that.  Maybe better to just set `resourceTypeGeneral` to `Other` then, since I don't think it's essential that the resource files are indexed by Google Dataset Search.

**Comment by GraemeWatt** [comment]
My [comments above](https://github.com/HEPData/hepdata/issues/162#issuecomment-943412364) on content negotiation were continued in private Zulip chat with @alisonrclarke and in a [comment on a pyhf issue](https://github.com/scikit-hep/pyhf/issues/1491#issuecomment-951810848).  To summarise, the DataCite media API is deprecated (see [blog post](https://blog.datacite.org/changes-to-doi-content-negotiation/)), and the simplest remaining approach is to implement content negotiation on the HEPData side so that, for example, `curl -LH "Accept: application/x-tar" https://doi.org/10.17182/hepdata.89408.v1/r2` would return the content (a `pyhf` tarball) instead of the HTML landing page.  More requests for refinements to content negotiation:

- [x] For the HEPData pages where JSON-LD is embedded, can we return the JSON-LD directly if a request is made with an `Accept: application/ld+json` header?
- [x] If a request is made like `curl -LH "Accept: application/ld+json" https://doi.org/10.17182/hepdata.89408.v1/r2` or `curl -LH "Accept: application/vnd.schemaorg.ld+json" https://doi.org/10.17182/hepdata.89408.v1/r2`, the JSON-LD will be returned from DataCite before getting to the HEPData page.  Therefore, if a user wants to retrieve JSON-LD from HEPData via the DOI, they would need to specify a custom metadata content type like `application/vnd.hepdata.ld+json` to get past the DataCite server.  So can we return JSON-LD from relevant HEPData pages if the media type is either `application/ld+json` or `application/vnd.hepdata.ld+json`?
- [x] If a user makes a request with an `Accept` header that we don't support (i.e. JSON-LD or the media type matching the resource file), can we return a [`406 Not Acceptable`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) error code with an error message listing the acceptable media types for the requested page?

Could you please try to address these points, @alisonrclarke ?

**Comment by matthewfeickert** [comment]
We've implemented the `Accept` header passing in https://github.com/scikit-hep/pyhf/pull/1673, so if there is anything that the `pyhf` dev team can help test please just let us know. :+1:
