### ISSUE TITLE
dashboard: resurrect and improve submissions view for a Coordinator

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#166]
A link to the endpoint `/dashboard/submissions` is currently hidden from a Coordinator's Dashboard (unless a user is Admin) because it has some problems.  It was originally intended to address #61.  The submissions view should be resurrected and refined, hiding submissions migrated from the old HepData site.

**Comment by alisonrclarke** [comment]
Once we've reduced the number of submissions shown we should check whether the search for the submissions is being done efficiently - currently the code aggregates by last updated day, then searches for each record in each day individually. Could we achieve the same results by ordering by last_updated and paginating through the full result set?

**Comment by GraemeWatt** [comment]
The submissions view fits in with a request today from Frank Geurts (Coordinator for STAR):

> As you can see I have a fairly large number of submissions that are all in various stages of progress towards official release. The dashboard functionality is nice if one has a handful but for the 38(!) that I am looking at it is less practical to quickly get relevant information.
>
> Is it possible that you can generate a spreadsheet (or some other exportable format) of the typically relevant fields that are associated with each entry. For example, I'd be interested in the HEPid, a direct link to the hepID, the title, the start date, names/emails of uploader(s), reviewer(s), associated arXiv/Inspire ID.

We could provide an "Export as CSV" button on the submissions view to generate the required information.

**Comment by GraemeWatt** [comment]
Bumping priority to "high" after another email today from @fgeurts (STAR):

> On a different topic, is there any news on tools that allow coordinators to view historical submission records for the organization that they represent? I think we talked about it a while ago but wasn't sure if something along those lines was already rolled out.

**Comment by GraemeWatt** [comment]
I've made a [post on the HEPData Forum](https://hepdata-forum.cern.ch/t/feedback-for-coordinator-submissions-view/25) to solicit feedback and I've notified all HEPData Coordinators by email of the post.

**Comment by alisonrclarke** [comment]
- [x] Enable a view just showing the current coordinator's submissions
- [x] Speed up the search on the backend
- [x] Add a CSV export showing e.g. HEPData id, link to record (with HEPData id?), title, start date, names/emails of uploader(s), reviewer(s), inspire ID.
- [x] Allow the admin user to view the submissions dashboard as a coordinator
- [x] Add a Coordinator bar chart (to work like the collaborations one)
- [x] Tidy up layout of dashboard top section (added button means it doesn't always fit)
- [x] Ensure view works for coordinator with no submissions 
- [x] Work out how to deal with last_updated dates from submission.yaml for imported records (does not reflect time added to HEPData.net)
