### ISSUE TITLE
dashboard: introduce pagination of submissions in progress

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#178]
The Dashboard can take quite a long time to load if there are a large number of submissions in progress.  This is more likely to be the case for an Admin user where unfinished records are shown from *all* Coordinators.  (Currently I see 218 submissions in progress on my Dashboard.)  It would be useful to introduce pagination of the submissions in progress, so only the most recent 25 (say) are shown initially, in a similar way to search results.

**Comment by alisonrclarke** [comment]
See #166 - pagination will depend on how we search for results.

**Comment by alisonrclarke** [comment]
I guess we want the filter to work across all submissions, not just the current page?

**Comment by GraemeWatt** [comment]
Yes, that would be better, otherwise the filter is of limited use.
