### ISSUE TITLE
dashboard: add option to manager widget to resend email invitations to Uploaders/Reviewers

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#191]
Request from Frank Geurts (STAR):

> I am the HEPdata coordinator for STAR. Over the past years I have come to realize that it would be really nice to have a feature that would allow me to resend the automated emails that usually are send when an uploader and reviewer are assigned.
> 
> I am not sure such a “resend invitation” option exists, but if it does then please point me to it. If it does not exists I think this would be a very welcome addition that will help send such reminders or (more often) address issues where the uploader/reviewer lost (read: deleted) the original email.

**Comment by zeynepaki** [comment]
@GraemeWatt should this option only be available if the invitation has not been accepted ?

**Comment by GraemeWatt** [comment]
I think the option should be available even if the invitation has been accepted.  The Uploader/Reviewer might have accepted the invitation months ago, but the Coordinator will still want to send a reminder to them to hasten progress.

**Comment by zeynepaki** [comment]
Hi Graeme! been trying a couple of things with this and had a couple of ideas of what can be done for it.
First we thought of adding the send reminder button next to the "accepted" status icon, which looks like this:
<img width="774" alt="option-3" src="https://user-images.githubusercontent.com/73976500/168844819-e9564a2b-3688-472e-9b74-1ea3d47bff52.png">
This would have made sense if it was only going to be available if people hadn't accepted it but in this case, it makes more sense having it displayed along with the other action buttons that are currently available like this:
![option-1](https://user-images.githubusercontent.com/73976500/168845487-e029f5d9-a1c0-4886-8bd3-9c9c9ec0361e.jpg)
I think this is fine, but looks a bit cluttered and would get even more cluttered over time if we had other stuff to add in the future. 
Which brings me to the third option to have a small popup with all the actions coming out if clicked on a button like this:
![option-2](https://user-images.githubusercontent.com/73976500/168846473-c85e3a9c-d1e8-432d-9f4a-a6311a8e17f0.jpg)
In this way we would not to worry about cluttering even if we decided to add more action buttons in the future.
Please let me know what you think and suggest any other ideas that you may have.
Ps. I whipped these up on photoshop so they would not be pixel-perfect to this on the live website.

**Comment by GraemeWatt** [comment]
Many thanks for mocking up the different options!  I don't have a strong preference, but the last pop-up option seems a bit complicated given that there will only be one action ("email") in the most common case of one primary Uploader/Reviewer.  The "demote" action only appears if there is a reserve participant and the "delete" action only appears for a reserve participant not a primary one.  We could reconsider in future if more actions need to be added, but I don't anticipate any at this stage.  I'm not sure it makes sense to send a email to a reserve participant, so the "email" option could only appear for a primary participant.  So I think the second mock-up will be fine if there are only a maximum of two actions (email/demote for primary and delete/promote for reserve), reducing the clutter.

**Comment by GraemeWatt** [comment]
Request from Frank Geurts (STAR):

> I am the HEPdata coordinator for the RHIC-STAR experiment and over the past many years I have noticed one important feature that would substantially improve one of the most performed tasks as a coordinator: resending the automated emails that invite uploaders/reviewers to go to their assigned HEPdata records.
>
> My feature request would therefore be, to simply add a button to each record that is still in progress that would resend the original email.
