### ISSUE TITLE
hepdata-cli: write a Python wrapper package to allow users to search and download data from the command line

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#198]
We have a basic API in that search results can be returned in JSON format by appending `&format=json` to the URL, e.g. a simple Python script:
```python
import requests
url = 'https://www.hepdata.net/search/?q=reactions:"P P--> LQ LQ X"&format=json'
response = requests.get(url)
data = response.json()
for result in data['results']:
   print(result['access_urls']['links'])
```
gives:
```javascript
{'csv': 'https://www.hepdata.net/download/submission/ins1462258/1/csv', 'json': 'https://www.hepdata.net/download/submission/ins1462258/1/json', 'root': 'https://www.hepdata.net/download/submission/ins1462258/1/root', 'yaml': 'https://www.hepdata.net/download/submission/ins1462258/1/yaml', 'yoda': 'https://www.hepdata.net/download/submission/ins1462258/1/yoda'}
```
with URLs for the data records in various formats.  Similarly, the individual data records and tables can be obtained in a JSON format.  A CLI tool could be written (in Python) called `hepdata-cli` that would take the search queries as arguments and return the data in one of the available formats.  This tool could perhaps also call the INSPIRE API to allow download by arXiv identifier, for example.

See also [INSPIRE Bibliographic Tools](https://old.inspirehep.net/info/hep/tools/index), the [arXiv API](https://arxiv.org/help/api) and the [arxiv-cli](https://pypi.org/project/arxiv-cli/) Python wrapper.

**Comment by GDeLaurentis** [comment]
[hepdata-cli](https://github.com/HEPData/hepdata-cli) closes this issue.
