### ISSUE TITLE
inspire_datasource: allow automatic updating of publication information

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#20]
_From @GraemeWatt on December 17, 2015 19:8_

HEPData records will typically be submitted before the corresponding paper is published in a journal and so the Inspire record will not have the DOI and journal reference at the time of HEPData submission.  It would be nice if a script could be run periodically to pull the latest metadata from Inspire (such as publication information) and update the HEPData record automatically.

_Copied from original issue: HEPData/hepdata#147_

**Comment by eamonnmag** [comment]
I've noticed submissions without journal information, I think this would obviously be useful. But should we run this once a month or once a week since Inspire won't be super happy if we ping them every day 8200 times :)

**Comment by eamonnmag** [comment]
This should be part of the load procedure too. What I'm thinking is an update command that updates all files (if files are provided), otherwise, if only and inspire id is provided, just updates the publication information.

**Comment by eamonnmag** [comment]
Done. I've added an update feature for the publication information and the data.

**Comment by alex-t-grecu** [comment]
I could not find this feature in the portal interface when I log in as Coordinator. Could you please, clarify where to search for it or how to proceed to really update the Inspire metadata? Thank you in advance.
