### ISSUE TITLE
Provide new label for likelihoods in hepdata record.

### ISSUE THREAD

**Issue by kratsg** [HEPData/hepdata#216]
```
- {description: 'Archive of full likelihoods in the HistFactory JSON format described in CERN-EP-2019-188. For each signal point the background-only model is found in the file named BkgOnly.json. All jsonpatches are contained in the file patchset.json. Each patch is identified in patchset.json by the metadata field "name": "C1N2_Wh_hbb_[m1]_[m2]" where m1 is the mass of both the lightest chargino and the next-to-lightest neutralino (which are assumed to be nearly mass degenerate) and m2 is the mass of the lightest neutralino.', location: 1Lbb-likelihoods-hepdata.tar.gz}
```

Currently, we upload likelihoods as a tarball that's under additional resources. As an example, the [ATLAS SUSY 1Lbb](https://www.hepdata.net/record/ins1755298) record has

<img width="886" alt="Screenshot 2020-06-02 09 51 50" src="https://user-images.githubusercontent.com/761483/83528101-afe14280-a4b6-11ea-9566-8d9e0fc4790f.png">

As you can see in bottom right, this shows up as a `gz File` label -- but it would be nice if this could be labeled explicitly "Likelihoods" or something similar with a different icon perhaps. Is this possible to do right now with the current `submission.yaml` or can we get it to be updated on hepdata reasonably soon? We'd like the ability to filter by analyses with public likelihoods uploaded on hepdata.

**Comment by GraemeWatt** [comment]
Yes, this is basically issue #163.  I'll try to look into it later this month.

**Comment by kratsg** [comment]
I wasn't aware (looks like only lukas was tagged).
