### ISSUE TITLE
cephfs is slow due to the large number of directories under /opt/hepdata/var/data

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#218]
@benjamin-bergia said:

> So I received a request from IT to look into our storage
> apparently there is 60k entries directly under /opt/hepdata/var/data (our mountpoint)
> it slows cephfs a lot
> I just tried to list the content of the directory and it takes few seconds
> if we could split these entries under some directories it will speed up the file accesses
> maybe grouping by the 2 first digits

After discussions with @GraemeWatt we're going to migrate to a new folder structure, either along the lines that @benjamin-bergia suggests, or using some sort of hash partitioning to ensure a more even distribution.

Individual file locations are stored in the `dataresource` table. cephfs is used for `CFG_DATADIR`.

Tasks:
 * [x] Refactor code so there's a common function to get the path for data files
 * [x] Check whether there are any places in the code which reference `CFG_DATADIR` rather then the entries in the `data resource` table for reading, and ensure they will still work whilst migration is happening
 * [x] Update where new submissions are stored
 * [x] Create a cli script to migrate old entries to use new paths (including converted files?)
 * [x] Create a cli command to get a directory name from a record id
 * [x] Check cli script copes with remote resource URLs as well as file system ones

**Comment by alisonrclarke** [comment]
IT have said that up to 1000 files/folders per directory should be OK.

Initial analysis of the current file list suggests that using a hashing algorithm and taking the first 2 characters of the digest gives a better spread than using the first 2 or 3 characters of the record id, e.g.:

```python
hash_object = hashlib.sha256(name.encode())
hex_dig = hash_object.hexdigest()
partition_name = str(hex_dig)[:2]
```

gives partitions with stats:

```
256 partitions
min no: 144
max no: 210
avg no: 178
```

whereas:
```python
partial_name = name
if partial_name.startswith('ins'):
    partial_name = partial_name[3:]

partition_name = partial_name[:3]
```

leads to more unevenly spread folders, which is likely to result in counts going over 1000:

```
944 partitions
min no: 1
max no: 1487
avg no: 48
```

**Comment by GraemeWatt** [comment]
Quite often I need to inspect the files on the disk to diagnose problems.  Currently it's easy to find the directory for a particular record given that record's ID.  If you decide to use a hashing algorithm, it would be useful to provide a CLI command to easily find a directory name given the record ID.

**Comment by GraemeWatt** [comment]
A separate, but related, issue is #139, i.e. delete unused files when a Sandbox record is deleted or a submission is replaced by a new upload.  Currently, only database entries are deleted and there is no cleanup of unused files from the disk.  Removing unused files would also reduce the number of directories.

**Comment by alisonrclarke** [comment]
I think it's worth doing #139 as part of moving the files around. (And the issue also clarifies some of my confusion over the file listings too.)
