### ISSUE TITLE
datacite: update metadata schema to latest version 4.4

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#225]
HEPData currently uses Version 3 of the [DataCite Metadata Schema](http://schema.datacite.org).  A request from Artemis Lavasa (@ArtemisLav) was made on 26th June 2020:

> As part of our relationship with DataCite, we are required to adhere to certain guidelines. There are a few action items that came up recently that I would like to ask each of you to address for your client accounts as soon as possible. More specifically, for each account:
> - Support the submission of metadata to DataCite that is compliant with DataCite Metadata Schema 4 or a more recent version. That means that if you are currently using version 3 of the schema or older, you will need to move to the newest one.

**Comment by alisonrclarke** [comment]
Started work on this on the `multiple-dois` branch. Simply changing the XML templates to use the new schema creates valid XML (see [test_xml_validates](https://github.com/HEPData/hepdata/blob/bb4a480da103aca7cdfd9129f2cc16615ba9c17f/tests/doi_minter_test.py#L201)  and some [example test DOIS](https://doi.test.datacite.org/dois/10.17182%2Fhepdata.466.v1%2Ft12)). 

I guess the question is whether we can/should add anything extra that's allowed by the updated schema? Details of the changes can be found at https://support.datacite.org/docs/datacite-metadata-schema-v44-earlier-version-update-notes

**Comment by GraemeWatt** [comment]
I think the existing XML templates are fine, but we could maybe use the new subproperty `resourceTypeGeneral` in `relatedIdentifier` that was added in version 4.2.  We could use `resourceTypeGeneral="JournalArticle"` for the journal DOI, `resourceTypeGeneral="Collection"` for the HEPData record DOI, and `resourceTypeGeneral="Dataset"` for the HEPData table DOIs.  I'm not sure there's an appropriate value for the INSPIRE record, so just miss it out.

Also, while looking at the DataCite docs for `alternateIdentifier`, I don't see that the 4 `/download/` links are appropriate here, so maybe better just to remove them.

**Comment by GraemeWatt** [comment]
For the data tables, the current XML gives the overall data abstract as a `description` with `descriptionType="Abstract"` and the table description is given with `descriptionType="Other"`.  But only the `Abstract` is shown in [DataCite Search](https://search.datacite.org/repositories/cern.hepdata) and not `Other`, so it's maybe better to swap the overall data abstract and the table description, i.e.
```xml
    <descriptions>
        <description descriptionType="Abstract">
            {{ table_description }}
        </description>

        <description descriptionType="Other">
            {{ overall_submission.data_abstract }}
        </description>
    </descriptions>
```
