### ISSUE TITLE
submission: use "yaml.safe_load()" instead of "yaml.load()"

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#23]
http://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML
"Warning: It is not safe to call `yaml.load` with any data received from an untrusted source!"

Similarly, use `yaml.safe_load_all()` instead of `yaml.load_all()`.

**Comment by eamonnmag** [comment]
Good catch @GraemeWatt!
