### ISSUE TITLE
records: change behaviour of "Revise Submission" button so upload not needed at the same time

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#231]
Currently, either Coordinators or Uploaders can create a new version by clicking the "Revise Submission" on the record.  However, they need to make an upload at the same time via the web interface, and upload is not possible via the CLI method for a finalised record.  I would prefer that only a Coordinator can click "Revise Submission" which creates a new version (a new `HEPSubmission` object with `todo` status), then the upload is done in a separate step (by either the Coordinator or an Uploader).  This makes the behaviour more similar for version 1 compared to later versions and it means that the Uploader can make the initial upload for version 2 (or later) via the CLI method if they prefer rather than relying on web upload.

**Comment by GraemeWatt** [comment]
It was recently pointed out by Frank Geurts (Coordinator by STAR) that an Uploader for the original version of a STAR record uploaded a second version by clicking "Revise Submission" without his knowledge.  Only the Coordinator should be able to click the "Revise Submission" button as described above.  I'll bump the priority.  This issue should be addressed with #230.

**Comment by alisonrclarke** [comment]
Should the coordinator be redirected to the dashboard after revising the submission, or to the new version of the record? (If the latter, should the 'upload' view of a 2nd (or more) version of a record show the 'Versions' button somewhere?)

**Comment by GraemeWatt** [comment]
Not sure, but maybe just to the Dashboard since a Coordinator will typically not upload at the same time.  An email invitation should be sent to the Uploader inviting them to upload the revised submission.  Yes, it would be good if the record page would show the versions button if nothing has yet been uploaded to the revised submission.

**Comment by alisonrclarke** [comment]
Do we need an actual invitation (suggesting we modify the participant record to change the status to pending and a new cookie) or just an email to say there's a new version with a link to upload?

**Comment by GraemeWatt** [comment]
A new cookie should not be needed for the revision.  I guess the `invite.html` template can be modified to include the record version and to only include the permissions link if it has not been claimed already, similar to what is done in the `upload.html` template for the Reviewer.  (There could be multiple Uploaders for the original version and only one has claimed permissions, or the Coordinator might have uploaded the original version.)  When the Coordinator clicks "Revise Submission", the Uploaders and Reviewers from the original version should be displayed.  The Coordinator should be able to enter an optional message for the Uploader, similar to creating a new submission.  There should also be an option *not* to send the Uploader email in case the Coordinator wants to change Uploaders/Reviewers between versions.  Some text should be displayed like "To change these Uploaders/Reviewers, add new ones from your Dashboard, then demote the original Uploaders/Reviewers.".

**Comment by alisonrclarke** [comment]
Just to check: should only the primary uploader be notified (if the coordinator decides to send notifications)?

**Comment by GraemeWatt** [comment]
Yes, `reserve` Uploaders don't play any role in the submission process until they are promoted to `primary`.
