### ISSUE TITLE
records: explicitly catch 413 error raised by too-large uploaded file

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#236]
The Kubernetes deployment at CERN recently replaced a Traefik Ingress controller with Nginx, with settings `client-max-body-size=50m` (50 MB, previously no limit) and `proxy-read-timeout=5m` (5 minutes, previously 1 minute).  The 50 MB upload limit is likely to be reached before the 5-minute timeout limit, therefore we should catch the 413 (Request Entity Too Large) error explicitly by modifying these lines:

https://github.com/HEPData/hepdata/blob/ba050a1ea010e0b12cb4c472ebc34320949e4549/hepdata/modules/records/static/js/hepdata_record_js.js#L74-L80

To allow local testing, we can add the Flask option [MAX_CONTENT_LENGTH](https://flask.palletsprojects.com/en/1.1.x/patterns/fileuploads/#improving-uploads) to `config.py`, i.e.

```python
# Limit the maximum allowed payload to 50 MB (same as used by Nginx in deployment at CERN).
MAX_CONTENT_LENGTH = 50 * 1024 * 1024
```
My problem is that I don't know how to check for a 413 status code in the above JavaScript snippet.  I thought I could use `e.status` but it just takes a value of 0, while `e.statusText` takes a value of `error`, when a `POST` request returns a 413 error (indicated in the main log of the web app) after uploading a file with size greater than the value of `MAX_CONTENT_LENGTH`.

**Comment by alisonrclarke** [comment]
We can check the file size before sending, which will allow us to give a more informative error message. Then I think we can just add further info to the unknown/unexpected error message with the status code and text from any remaining errors. (We can use extra params to the error function to retrieve those values.)
