### ISSUE TITLE
records: links to cmenergies above data tables not working properly

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#240]
The links are constructed in these lines:
https://github.com/HEPData/hepdata/blob/5d46e29bba56549f084cdaca8d843ae44a3c8f45/hepdata/modules/records/static/js/hepdata_tables.js#L214-L216

Example: the first table of https://www.hepdata.net/record/ins73968 has a link [cmenergies=1.243-1.362](https://www.hepdata.net/search?q=&cmenergies=1.243-1.362), which I think just need to be changed to [cmenergies=1.243,1.362](https://www.hepdata.net/search?q=&cmenergies=1.243,1.362).

But for single values like [cmenergies=1960.0](https://www.hepdata.net/search/?q=&cmenergies=1960.0) some of the search results do not seem to make sense.  A narrow range like [cmenergies=1959.9,1960.1](https://www.hepdata.net/search/?q=&cmenergies=1959.9,1960.1) works but a zero range like [cmenergies=1960.0,1960.0](https://www.hepdata.net/search/?q=&cmenergies=1960.0,1960.0) gives `ValueError: range() arg 3 must not be zero` from the line:
https://github.com/HEPData/hepdata/blob/5d46e29bba56549f084cdaca8d843ae44a3c8f45/hepdata/ext/elasticsearch/aggregations.py#L173

@alisonrclarke, since this is related to changes you made previously to treat `cmenergies` as a number instead of a string in the Elasticsearch index, could you please try to find a solution to this issue when you have time?

**Comment by alisonrclarke** [comment]
> But for single values like cmenergies=1960.0 some of the search results do not seem to make sense. A narrow range like cmenergies=1959.9,1960.1 works but a zero range like cmenergies=1960.0,1960.0 gives `ValueError: range() arg 3 must not be zero`

I think cmenergies=1960 works as expected. I'll take a look at the zero range error as well as the JS links, but can I check whether that link appeared anywhere on the page or whether it's just something you typed?

**Comment by alisonrclarke** [comment]
> > But for single values like cmenergies=1960.0 some of the search results do not seem to make sense. A narrow range like cmenergies=1959.9,1960.1 works but a zero range like cmenergies=1960.0,1960.0 gives `ValueError: range() arg 3 must not be zero`
> 
> I think cmenergies=1960 works as expected. I'll take a look at the zero range error as well as the JS links, but can I check whether that link appeared anywhere on the page or whether it's just something you typed?

I've just realised that `cmenergies=1960` does a search for `cmenergies >= 1960`. I'll change it to only search for ranges including 1960 - does that sound reasonable?

**Comment by GraemeWatt** [comment]
Looks great, thanks, I've tested and merged the PR.  No, a link like `cmenergies=1960.0,1960.0` didn't appear anywhere, but was just my guess at a possible URL.  OK, it makes sense now that `cmenergies=1960.0` gave results for `>=` 1960, but I agree that it should search for ranges including 1960 instead.

**Comment by alisonrclarke** [comment]
This still seems to happening on some records, e.g. https://www.hepdata.net/record/ins147683?version=1&table=Table%2051  gives an error message:

> Unable to search for : failed to create query: { "bool" : { "filter" : [ { "term" : { "doc_type" : { "value" : "publication", "boost" : 1.0 } } }, { "range" : { "data_keywords.cmenergies" : { "from" : 1.48, "to" : 1.479, "include_lower" : true, "include_upper" : true, "boost" : 1.0 } } } ], "adjust_pure_negative" : true, "boost" : 1.0 } }

**Comment by GraemeWatt** [comment]
This happens because the range is the wrong way around in the [original migrated table](http://hepdata.cedar.ac.uk/view/ins147683/d51):
```yaml
- {name: cmenergies, values: [1.48-1.479]}
```
In [`process_cmenergies`](https://github.com/HEPData/hepdata/blob/8bbc1281ad43e4193a06269465b4a70e2a763604/hepdata/ext/elasticsearch/document_enhancers.py#L123) there is some code that swaps the limits if they are the wrong way around.  Something similar should be done in the JavaScript code that constructs the search link in `hepdata_tables.js`.

**Comment by alisonrclarke** [comment]
Decided to change this in python when we add the cmenergies filter to the elasticsearch query - feels more robust that way round.
