### ISSUE TITLE
tests: test_receive_before_flush_errors failing on my laptop

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#265]
When running the tests locally on my laptop (macOS) I get an error:
```
FAILED tests/model_test.py::test_receive_before_flush_errors - assert 4 == 2
```
due to this line:
https://github.com/HEPData/hepdata/blob/5da5dfe3376370606e266c01a58c05dfdcac29f9/tests/model_test.py#L169
If I print out `caplog.records` I get:
```
[<LogRecord: hepdata.modules.submission.models, 10, /Users/graemewatt/src/hepdata/hepdata/modules/submission/models.py, 183, "Deleting data resource None">, <LogRecord: hepdata.modules.submission.models, 40, /Users/graemewatt/src/hepdata/hepdata/modules/submission/models.py, 190, "Unable to delete data resource with id None whilst deleting data submission id 1. Error was: Instance '<DataResource at 0x7f8ab93b6fd0>' is not persisted">, <LogRecord: hepdata.modules.submission.models, 10, /Users/graemewatt/src/hepdata/hepdata/modules/submission/models.py, 192, "Deleting reviews for data submission 1">, <LogRecord: hepdata.modules.submission.models, 40, /Users/graemewatt/src/hepdata/hepdata/modules/submission/models.py, 200, "Unable to delete review with id None whilst deleting data submission id 1. Error was: Instance '<DataReview at 0x7f8ab93c40b8>' is not persisted">]
```
i.e. 4 entries in the list rather than the expected 2.  The test passes when run as a GitHub Actions [workflow](https://github.com/HEPData/hepdata/runs/1389297468?check_suite_focus=true).

**Comment by alisonrclarke** [comment]
It looks like `caplog` is including `DEBUG` level output despite the line:

```
caplog.set_level(logging.ERROR)
```

The only way I get the same error locally is if I comment out that line.

Can I check what version of pytest you're using? I'm on v6.0.2. Wondering whether it's worth updating setup.py to use `pytest>=6.0`?

**Comment by GraemeWatt** [comment]
Yes, the `pytest` version seems to be the problem.  I was using v5.4.3.  The test passes after upgrading to v6.1.2.
