### ISSUE TITLE
celery: look into acks_late and reject_on_worker_lost task settings.

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#266]
Micha says:

> We set acks_late on all idempotent jobs (or at least jobs that have side-effects which are mild enough that retrying them even if they've been run already is not a big issue), and automatically add the second option for those: https://github.com/inspirehep/inspirehep/blob/19d8ffb07caeb0da53746482c54612055298ec38/backend/inspirehep/config.py#L142-L149

We should look into the `acks_late` and `reject_on_worker_lost` settings.

**Comment by GraemeWatt** [comment]
These options might help with the `WorkerLostError` exception mentioned in my [comment](https://github.com/HEPData/hepdata/issues/248#issuecomment-771774109) of issue #248.
