### ISSUE TITLE
records: use "du" instead of "legacy_version" after old.inspirehep.net is switched off

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#287]
We currently check which INSPIRE records have been updated using a query:

https://github.com/HEPData/hepdata/blob/4b5c869ca7d9cabacb6b284f7196d0807fb484de/hepdata/modules/records/utils/records_update_utils.py#L186-L188

After [old.inspirehep.net](https://old.inspirehep.net) is switched off, the `legacy_version` field will stop updating and might disappear.  Instead, we should query by `_updated` or equivalently `du` (date updated), i.e.

```python
    url = ('https://inspirehep.net/api/literature?sort=mostrecent&size={}&page={}'.format(size, page) +
           '&q=external_system_identifiers.schema%3AHEPData%20and%20du%3A{}'.format(specified_time.strftime("%Y-%m-%d")) +
           ('' if on_or_since == 'on' else '%2B'))
```
However, we apparently shouldn't rely on this before [old.inspirehep.net](https://old.inspirehep.net) is switched off.  Comment from @michamos:

> It's currently meaningless as it reflects when the record has last been updated on the new system, which might happen even without underlying changes to the record.

**Comment by GraemeWatt** [comment]
I've tried making this change, but it causes some problems with the tests.  The test [`test_get_updated_records_on_date`](https://github.com/HEPData/hepdata/blob/d366fcfe30fdce0cadff00359d9cef04ef2eed31/tests/records_test.py#L503) fails because the INSPIRE record [1650066](https://inspirehep.net/literature/1650066) was updated on 2021-06-25.  The test [`test_get_updated_records_since_date`](https://github.com/HEPData/hepdata/blob/d366fcfe30fdce0cadff00359d9cef04ef2eed31/tests/records_test.py#L494) fails with a timeout because 4889 records were updated on 2021-06-25, 3878 records were updated on 2021-06-26, 116 records were updated on 2021-06-27 and 498 records (so far) were updated on 2021-06-28.  The tests could be relaxed so they pass, for example, just check the last two days in `test_get_updated_records_since_date`, but it's probably easier just to wait a few days until the updates have stabilised before addressing this issue.

**Comment by michamos** [comment]
I don't know exactly what your tests are expecting, but in general we expect many more record updates compared to the old system, as there's much more metadata that is kept in the record itself instead of auxiliary structures, most notably associations with author profiles and claims.
