### ISSUE TITLE
records: provide an endpoint giving all HEPData or INSPIRE record IDs

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#290]
The old HepData site had an endpoint http://hepdata.cedar.ac.uk/allids giving a list of all record IDs (INSPIRE, SPIRES, HepData).  An optional date could be added to restrict to records added or modified after a particular date, e.g.

- http://hepdata.cedar.ac.uk/allids/2014 (records modified since the beginning of 2014)
- http://hepdata.cedar.ac.uk/allids/201312 (records modified since the beginning of December 2013)
- http://hepdata.cedar.ac.uk/allids/20131215 (records modified since 15th December 2013)

The `allids` endpoint is invoked in the [get_all_ids_in_current_system](https://github.com/HEPData/hepdata/blob/fd2908404f730c716e88054a453ea0489a7e44d4/hepdata/modules/records/migrator/api.py#L168) function of the current [records/migrator/api.py](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/records/migrator/api.py), which was used to migrate records from [hepdata.cedar.ac.uk](http://hepdata.cedar.ac.uk) to [hepdata.net](https://www.hepdata.net) in 2016.  For importing records from [hepdata.net](https://www.hepdata.net) into a local instance (issue #275), it would be useful to implement something similar to the old `allids` endpoint, i.e. a concise list of HEPData or INSPIRE IDs of all finalised records probably in JSON format (without pagination).  An option to filter by the `last_updated` date might also be useful.

Such an endpoint would have other applications such as providing an easier way for users to make bulk downloads.

**Comment by alisonrclarke** [comment]
By HEPData id do you mean record ID or the quoted inspire id e.g. `"ins12345"`?

**Comment by GraemeWatt** [comment]
> By HEPData id do you mean record ID or the quoted inspire id e.g. `"ins12345"`?

Ideally both, but not at the same time.  For example, maybe a list of the HEPData record IDs by default, but allow a URL option to instead return a list of the INSPIRE record IDs.  The `last_updated` filter could also be specified by a URL option.
