### ISSUE TITLE
security: switch to new CERN Single Sign-On

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#297]
Over the last year, CERN websites have been gradually moving to use a [new Single Sign-on (SSO) portal](https://home.cern/news/news/computing/computer-security-new-single-sign).  This means that the old CERN SSO authentication system will be phased out in the short term and no longer maintained.  Today I upgraded the [HEPData Forum](https://hepdata-forum.cern.ch) to use the new CERN SSO following a request from the CERN Discourse Service.  The old [CERN SSO Management](https://sso-management.web.cern.ch/) website no longer allows users to register new websites, which should instead be done from the new [CERN Application Portal](https://application-portal.web.cern.ch/).  The HEPData "Sign up with CERN" and "Log in with CERN" options should be changed to use the new CERN SSO.  See [Configuring your application](https://auth.docs.cern.ch/applications/application-configuration/) by the CERN Authorization Service.  Currently we use [Invenio-OAuthClient](https://github.com/inveniosoftware/invenio-oauthclient) v1.1.3, which would need to be upgraded to use [CERN OIDC](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/cern_openid.py).

**Comment by alisonrclarke** [comment]
Looks like we'd need to upgrade invenio-oauthclient to v1.4.0 at a minimum. Doing that in my local environment pulls in the following:

```
Successfully installed Flask-KVSession-Invenio-0.6.3 invenio-accounts-1.4.3 invenio-assets-1.2.5 invenio-base-1.2.3 invenio-celery-1.2.2 invenio-i18n-1.3.0 invenio-oauthclient-1.4.0 invenio-rest-1.2.3 invenio-theme-1.3.7 marshmallow-3.10.0 webargs-5.5.3
```

So I think we'll need to tackle #138 before we can do this. I think the biggest change is in `Invenio-assets` which moved from flask-assets and AMD/RequireJS to webpack in v1.2.0 - see the [upgrade guide](https://invenio-assets.readthedocs.io/en/latest/upgrade.html).

**Comment by GraemeWatt** [comment]
Thanks for investigating.  The old CERN SSO will keep working until at least next year, but we should aim to upgrade by the end of 2021.  In any case, it's a good idea to upgrade the Invenio packages (#138).
