### ISSUE TITLE
submission: check that data sent to converter is less than UPLOAD_MAX_SIZE

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#304]
The [Kubernetes configuration](https://github.com/inspirehep/kubernetes/blob/0949ae01b0a905207909f528f5dcc8da13e4744f/nginx-ingress/kustomization.yml#L28) has `client-max-body-size=50m`.  The HEPData submission code checks that the uploaded archive file is less than a variable:
https://github.com/HEPData/hepdata/blob/bb8f2c35e5e9cc2791b5d46bf3af3b053572703e/hepdata/config.py#L146

However, regardless of the format of the uploaded archive file (`.zip`, `.tar`, `.tar.gz`, `.tgz`), a zip file is created on disk that is later passed to the converter (for download in YAML, YODA, ROOT or CSV formats).  It's possible that the original archive file is less than 50 MB (maybe created with strong compression), but the created zip file is greater than 50 MB.  This means that the conversion will fail even if the original submission was successful, as for https://www.hepdata.net/record/99806?version=1 .  Here the original upload `submission_v7c.tar.gz` was 50767132 bytes (49 MB), but the created `HEPData-99806-v1-yaml.zip` file is 54004007 bytes (52 MB).

To avoid this problem, the submission code should check if the created zip file is less than `UPLOAD_MAX_SIZE`, returning an error message otherwise.  We could also investigate if using non-default compression options of [zipfile.ZipFile](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile) could give a smaller zip file without substantially compromising on speed.

**Comment by GraemeWatt** [comment]
I've investigated further and it seems the situation is more complicated than I initially thought.

Firstly, the default behaviour of [zipfile.ZipFile](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile) is no compression.  An option `compression=ZIP_DEFLATED` can be set to enable compression, and `compresslevel=9` (default is 6) enables maximum compression.  Alternatively, a high-level Python function [shutil.make_archive](https://docs.python.org/3/library/shutil.html#shutil.make_archive) could be used instead of `zipfile.ZipFile`, since the former compresses zip files by default.  The command-line `zip` utility also compresses by default and can be used with a `-9` option to enable maximum compression.  Using any of these compression options reduces the `HEPData-99806-v1-yaml.zip` file of https://www.hepdata.net/record/99806?version=1 to 49 MB, a similar size to the original upload `submission_v7c.tar.gz`.  However, the conversion still fails.

Looking at the HEPData code more closely, it is not the `HEPData-99806-v1-yaml.zip` file that is passed directly to the converter.  Data is passed to the `/convert` endpoint of the converter by [this line of the hepdata-converter-ws-client](https://github.com/HEPData/hepdata-converter-ws-client/blob/08485154dc6bc1d89433467571382da67bea73b7/hepdata_converter_ws_client/__init__.py#L103), i.e. a zipped tar file object created from the `input` path.

For the `/download/submission` endpoints, the input path is set in this line:
https://github.com/HEPData/hepdata/blob/58206261cc0f16b19d7f43a41907b45982e84b8d/hepdata/modules/converter/__init__.py#L63
Here the `input_directory` is a temporary directory created by extracting the `HEPData-99806-v1-yaml.zip` file:
https://github.com/HEPData/hepdata/blob/58206261cc0f16b19d7f43a41907b45982e84b8d/hepdata/modules/converter/__init__.py#L47-L48
These lines could be modified so that only the `.yaml` files are extracted.  This would reduce the size of the directory from 52 MB to only 620 KB.  (Probably `.json` files should also be extracted, given that JSON is an alternative table format to YAML.)  I temporarily replaced `HEPData-99806-v1-yaml.zip` with a version containing only YAML files, and clicked "Download All" for each format to store the converted submissions in the `converted` directory.

For the `/download/table` endpoints, the input path is `record_path` set in this line:
https://github.com/HEPData/hepdata/blob/58206261cc0f16b19d7f43a41907b45982e84b8d/hepdata/modules/converter/views.py#L498
i.e. the location of the original files.  This means that many unnecessary files are passed to the `/convert` endpoint of the converter.  In principle, only the `submission.yaml` file and a single YAML data file are needed to convert a single table.  However, the current [hepdata-converter](https://github.com/HEPData/hepdata-converter) code is not set up to convert a single table this way.  As for the `/download/submission` endpoints, it would be better to create a temporary directory containing only `.yaml` (and `.json`) files that's passed to the converter.

To avoid repeatedly creating temporary directories every time a submission or table is converted, maybe a step could be added at the end of [package_submission](https://github.com/HEPData/hepdata/blob/58206261cc0f16b19d7f43a41907b45982e84b8d/hepdata/modules/records/utils/submission.py#L577), after creating the `HEPData-99806-v1-yaml.zip` file, where a directory like `HEPData-99806-v1-yaml-convert` could be created, containing only YAML files.  Then the converter code would pass this directory to `hepdata_converter_ws_client.convert` if it already exists, otherwise the directory would be created first and the YAML files copied into it.  We can then check that the size of the `HEPData-99806-v1-yaml-convert` directory (not compressed) is less than `UPLOAD_MAX_SIZE`, returning an error message otherwise.

**Comment by alisonrclarke** [comment]
Thanks for digging further. A couple of questions:

1. Should I still also be looking at changing the compression level when creating the archive file as well as the converted dir?
2. Do you think there would be any issue with disk space/number of files if we create the directory with just the yaml/json files and leave it there permanently?
3. Would it make sense to create that directory on the first conversion attempt rather than when processing an upload, so it's only created when needed?

**Comment by GraemeWatt** [comment]
1.  This is optional now that I know it's not the source of the problem, so maybe simpler just to leave it for now.
2. My proposal does create duplicate files and is not ideal, but it's the simplest solution I could think of on Friday without modifying the converter packages.  I'm open to alternative suggestions.
3. I think the directories like `HEPData-99806-v1-yaml-convert` need to be created at the end of the submission stage, so that the size of the (uncompressed) directory can be checked, and the submission rejected if it's greater than `UPLOAD_MAX_SIZE`.  Otherwise, it could be possible for a user to submit a compressed archive (say, 49 MB) containing only YAML files, which is more than 50 MB uncompressed and hence gives an error from the converter.

**Comment by GraemeWatt** [comment]
Maybe it would be better to modify [this line](https://github.com/HEPData/hepdata-converter-ws-client/blob/08485154dc6bc1d89433467571382da67bea73b7/hepdata_converter_ws_client/__init__.py#L82) of [hepdata-converter-ws-client](https://github.com/HEPData/hepdata-converter-ws-client) so that only `.yaml` (and possibly `.json`) files are added to the tar archive file object that's later passed to the `/convert` endpoint of the converter web service.  This would avoid creating any extra directories with duplicate files like `HEPData-99806-v1-yaml-convert`.

A check should still be made at the end of the submission process that the YAML/JSON included in the upload are still less than `UPLOAD_MAX_SIZE` to avoid later conversion problems.

**Comment by alisonrclarke** [comment]
I'm working on this on the client, and testing with ins1831992 (record 99806 on hepdata.net as mentioned previously) sends only around 213 kB of json. It seems unlikely that anyone will upload a record that contains 50MB of yaml alone without being too big to upload in the first place (see below), so do you still think we need to do additional checks at the end of the submission process?

(I'm assuming that as discussed, the original issue was due either to the additional json payload sent to the converter, or to a difference between power of 10 and power of 2 in the MB calculation between flask and kubernetes.)

**Comment by GraemeWatt** [comment]
Yes, it's unlikely, so a check might not be necessary.  It still might be useful if you can easily return an error message from [package_submission](https://github.com/HEPData/hepdata/blob/2154b8c943fdaf8170775546d8c55787b96f7e25/hepdata/modules/records/utils/submission.py#L581).  The point I didn't yet understand is whether the payload sent to the converter is compressed or uncompressed, since we'd need to make the same compression choice in the check in `package_submission`, and it might not be worthwhile if it's complicated.  Is the 213 KB you mention the size of `data` passed to `/convert` when you restrict only to YAML files?  This would suggest compressed, since I think the uncompressed YAML files are 620 KB.  What's the size of the `data` payload sent to the converter without restricting only to YAML files?  I think the `client-max-body-size=50m` of the Kubernetes configuration must be 52428800 bytes, otherwise the original upload `submission_v7c.tar.gz` 50767132 bytes would have failed if `50m` meant 50000000 bytes, so I don't see that's an explanation.

**Comment by alisonrclarke** [comment]
> The point I didn't yet understand is whether the payload sent to the converter is compressed or uncompressed, since we'd need to make the same compression choice in the check in package_submission, and it might not be worthwhile if it's complicated.

The data is compressed (uses `tarfile.open(mode='w:gz', fileobj=input_stream)` in [line 84 of __init__.py](https://github.com/HEPData/hepdata-converter-ws-client/blob/08485154dc6bc1d89433467571382da67bea73b7/hepdata_converter_ws_client/__init__.py#L84), but the JSON which wraps it isn't compressed. One way to check would be to add a method to hepdata-converter-ws-client to check the JSON size (refactoring the json creation to a separate function), so that we can be sure the check compresses things the same way as the client.

> Is the 213 KB you mention the size of data passed to /convert when you restrict only to YAML files?

Yes. Once the non-yaml files are removed, request content-length is 213092; response content-length is 150648.

> What's the size of the data payload sent to the converter without restricting only to YAML files?

67561340 bytes! If I write the tar to disk using the same compression it comes out at 50670857 bytes, so it's not the compression that's the issue; it looks like the base64 encoding to convert to json adds a lot of overhead for the binary files. (Perhaps it would be more efficient to send the file as the request body without encoding, and the options as URL parameters, but that's a separate issue.)

**Comment by GraemeWatt** [comment]
Thanks for investigating.  Interesting that the Base64 encoding increases the payload size for binary files, but at least we have an explanation now.

> One way to check would be to add a method to hepdata-converter-ws-client to check the JSON size (refactoring the json creation to a separate function), so that we can be sure the check compresses things the same way as the client.

Could this be done before I make a new release v0.1.7 of [hepdata-converter-ws-client](https://github.com/HEPData/hepdata-converter-ws-client) if you think it's worthwhile?

**Comment by alisonrclarke** [comment]
> Thanks for investigating. Interesting that the Base64 encoding increases the payload size for binary files, but at least we have an explanation now.
> 
> > One way to check would be to add a method to hepdata-converter-ws-client to check the JSON size (refactoring the json creation to a separate function), so that we can be sure the check compresses things the same way as the client.
> 
> Could this be done before I make a new release v0.1.7 of [hepdata-converter-ws-client](https://github.com/HEPData/hepdata-converter-ws-client) if you think it's worthwhile?

You might be a better judge of whether it's worthwhile than I am :) Can you think of a situation where a submission would consist of 50MB of yaml?

**Comment by GraemeWatt** [comment]
Yes, it could definitely happen that a submission could contain 50 MB of YAML files, although it's unlikely.  The question is whether the Base64 encoding adds significant overhead in this case.  If the original upload was a 49 MB `.tar.gz` file containing only YAML files, the submission process would succeed, but the converter might still fail if the Base64 encoding to JSON pushed the size over 50 MB.  In the YAML-only case you mentioned above where the request content-length is 213092 bytes, what's the size of the compressed tar file if you write to disk?  I get 159635 bytes from running `tar zcvf` on my laptop, which means the fractional added overhead for only YAML files is exactly the same (33%) as for all files.  So I still think it's worth making a check at the submission stage, but it's a lower priority than your existing fix made in HEPData/hepdata-converter-ws-client#10.  I'll make a new release v0.1.7 of the hepdata-converter-ws-client now, then further changes can be made in a future release.
