### ISSUE TITLE
converter: use 'any' for file_format parameter in routes

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#312]
The download links for individual tables have Flask routes like:
https://github.com/HEPData/hepdata/blob/2154b8c943fdaf8170775546d8c55787b96f7e25/hepdata/modules/converter/views.py#L327-L330
Recently I noticed a problem with some tables in https://www.hepdata.net/record/ins778396?version=2 where the first table name is "Figure 6, pp, part 2/2".  The YAML download link is:
```
https://www.hepdata.net/download/table/ins778396/Figure%206,%20pp,%20part%202/2/2/yaml
```
This should match `/table/<inspire_id>/<path:table_name>/<file_format>`, but the presence of the forward slash followed by an integer in the table name means that it actually matches `/table/<inspire_id>/<path:table_name>/<int:version>/<file_format>/<rivet>`.  An error is then returned because the table name `Figure 6, pp, part 2` cannot be found in the database.  URL-encoding the `/` in the table name does not help.

A possible solution is to use the Werkzeug [AnyConverter](https://github.com/pallets/werkzeug/blob/2b2c4c3dd3cf7389e9f4aa06371b7332257c6289/src/werkzeug/routing.py#L1136) to restrict the `file_format` parameter to its possible values, i.e. replace `<file_format>` by `<any(json, yaml, yoda, root, csv):file_format>` in the routes.  I've checked that this solution fixes the problem.

**Comment by kratsg** [comment]
I think this bit scikit-hep/uproot4#269 . We're relying on this URL: https://www.hepdata.net/download/table/ins1755298/Expected%20limit%201lbb/3/root (which was working in the past but now is not).
