### ISSUE TITLE
submission: preserve date stamp for each version of a record

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#35]
Currently, the "Last updated" date displayed on each record is always of the most recent version, regardless of the selected version.  Instead it would be better to preserve a date stamp for each version, and display the corresponding date stamp for the selected version.  (This is like the arXiv model of versioning that we are trying to follow.)  If there are multiple data versions, a user will want to know when exactly the earlier versions were updated, and not just the date of the most recent version.

**Comment by eamonnmag** [comment]
Closed for now as not required.
