### ISSUE TITLE
ci: run tests nightly on master branch

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#355]
It occasionally happens that a new version of a package is released that breaks the build or the tests.  Often the failure is not apparent until days later when a commit is pushed or a new PR is opened.  It is then not clear whether the failure is due to the new commit/PR or to an upgraded package.  A recent example was the upgrade of [webpack-bundle-tracker](https://github.com/django-webpack/webpack-bundle-tracker) from v1.0.0-alpha.1 to v1.0.0 which broke [invenio-assets](https://github.com/inveniosoftware/invenio-assets) v1.2.5 (fixed by inveniosoftware/invenio-assets#138 in v1.2.6).  Another occasional source of failure is due to changes in external services like updates to [INSPIRE](https://inspirehep.net) records (see PR #354).  To isolate build/test failures due to new package releases or other external factors from those due to new commits/PRs, it would be useful to run the tests nightly on the `master` branch.

**Comment by alisonrclarke** [comment]
Is it OK to push the nightly builds to dockerhub or should we adjust the condition for the `deploy` job to only work on `push` or `release`?

**Comment by GraemeWatt** [comment]
I think it should be OK to push to Docker Hub nightly.  It's useful to test the build of the Docker image nightly and the existing tag on Docker Hub will just be overwritten.
