### ISSUE TITLE
resources: allow files with any extension to be downloaded

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#36]
Some of the migrated records have attached files that cannot be downloaded, for example:
https://hepdata.net/record/ins1268975 (two .tgz files attached as additional publication resources)
https://hepdata.net/record/ins838435 (one .tab.gz file attached as additional publication resources)
There should be no restrictions made on the filename extension of additional resources.

**Comment by eamonnmag** [comment]
Thanks Graeme! Will check this out tomorrow.
