### ISSUE TITLE
records: add missing associated_recid and publication_inspire_id to datasubmission

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#370]
Some `datasubmission` database tables of finalised records have a null `associated_recid` and `publication_inspire_id`, specifically version 1 of these records:

```sql
hepdata=> select distinct(datasubmission.publication_recid) from datasubmission, hepsubmission where datasubmission.associated_recid is null and datasubmission.publication_inspire_id is null and hepsubmission.overall_status='finished' and hepsubmission.publication_recid=datasubmission.publication_recid and hepsubmission.version=datasubmission.version order by datasubmission.publication_recid;
 publication_recid 
-------------------
              5477
             15988
             18381
             21666
             23151
             31972
             34612
             61925
             73908
             75023
             75115
             75323
             76245
             76247
             76740
(15 rows)
```
The fields `associated_recid` and `publication_inspire_id` should have been added by the `finalise_datasubmission` function:
https://github.com/HEPData/hepdata/blob/ac009974b012493f6b04133283ff16b64cc62b52/hepdata/modules/records/utils/submission.py#L905-L906
But the finalisation must have partially failed for these records when migrating from the old HepData site in 2016.  It should be straightforward to set the `publication_inspire_id` to be the same as the `inspire_id` of the `hepsubmission` table with the same `publication_recid`.  But it's not clear how to recover the correct `associated_recid`, so part of the finalisation process might need to be repeated to create new data records if they do not already exist.

The missing `publication_inspire_id` means that the download links for individual tables are currently broken.  The missing `associated_recid` means that data tables do not appear in searches.  This issue was identified when running `hepdata utils cleanup-index` which gave a [Sentry exception](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/17674/?query=is%3Aunresolved) for https://www.hepdata.net/record/15988?version=1 due to the null `associated_recid` values.  [This line](https://github.com/HEPData/hepdata/blob/a64ee94f7e47892907e4896de22c23bc92674da6/hepdata/ext/elasticsearch/api.py#L315) of `cleanup_index_batch` could be modified to filter out `None` values.  However, it should not be necessary to run `hepdata utils cleanup-index` again now that the indexing code has been improved.

**Comment by alisonrclarke** [comment]
Some of the data submission records had matching records in `records_metadata`, and I've used a DB script to update the data submission records with the `publication_inspire id` and `associated_recid`.

Others apparently did not have a record created, or DOI registered, so I will add a CLI script to finalise those data submissions and register the DOIs.
