### ISSUE TITLE
datacite: use collaboration name as "creator" instead of individual authors

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#377]
The XML metadata pushed to DataCite ([datacite_container_submission.xml](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_container_submission.xml) and [datacite_data_record.xml](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_data_record.xml)) includes the full list of authors as `creators`.  We had a request from the [Data Citation Index](https://clarivate.com/webofsciencegroup/solutions/webofscience-data-citation-index/) to include the collaboration name in the XML metadata.  This could be done using, for example, "ATLAS Collaboration" as `creatorName` and "Organizational" as `nameType` **instead** of the full list of authors, drastically reducing the size of the XML metadata for large collaborations consisting of thousands of authors.  Multiple collaborations should each have a `creator` entry.  If there is no collaboration, the full list of authors can be given as before, but with "Personal" as `nameType`.  I've checked with Artemis Lavasa (DataCite manager at CERN) that this solution is acceptable, and it has in fact been followed for years by CERN Open Data.  This issue should be addressed with #225, i.e. updating the DataCite metadata schema version.  Reducing the XML metadata size might also help with the problem mentioned in #318, i.e. failures when pushing XML metadata to DataCite.  After this issue is closed and the new code deployed, it will be necessary to run `hepdata doi-utils register-dois` to push the updated XML metadata to DataCite for all finished records.

**Comment by alisonrclarke** [comment]
Work started on `multiple-doi-tasks` branch. Samples of new metadata from my local instance can be seen at https://doi.test.datacite.org/repositories/cern.hepdata/dois

**Comment by GraemeWatt** [comment]
Looks good, thanks.  Can you please add the word "Collaboration" in the `creatorName`, i.e. `{{ collaboration }} Collaboration`?
