### ISSUE TITLE
docs: broken Read the Docs build for "CLI Commands"

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#378]
The Read the Docs page on [CLI Commands](https://hepdata.readthedocs.io/en/latest/cli.html) does not display any commands, although it works fine when building the docs locally.  The most recent Read the Docs build is shown as "Passed", but warnings can be found in the [build log](https://readthedocs.org/api/v2/build/14152384.txt):

```
 /home/docs/checkouts/readthedocs.org/user_builds/hepdata/checkouts/latest/docs/cli.rst:33: WARNING: Failed to import "importer" from "hepdata.cli". The following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hepdata/envs/latest/lib/python3.6/site-packages/sphinx_click/ext.py", line 385, in _load_module
    mod = __import__(module_name, globals(), locals(), [attr_name])
  File "/home/docs/checkouts/readthedocs.org/user_builds/hepdata/envs/latest/lib/python3.6/site-packages/hepdata/cli.py", line 529, in <module>
    for filename in os.listdir(fixes_path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/hepdata/envs/latest/lib/python3.6/site-packages/fixes'
```

**Comment by alisonrclarke** [comment]
This is to do with the way sphinx installs the `hepdata` package: as it doesn't use `pip install -e` (which we do as developers, and as is done in the docker build), `hepdata` its installed in the `site-packages` dir, so the `fixes` directory, which is not part of the package, can't be found. (It was a deliberate decision to keep these temporary fixes outside of the package.)

My proposed fix (currently on my fork of the repo so I can check readthedocs) simply checks for the existence of the fixes directory before attempting to import its modules. The CLI page on ReadTheDocs therefore won't be able to list individual `fix` commands but it probably doesn't need to given they're temporary, and I've updated the docstring to show how to list the `hepdata fix` subcommands.

Let me know if you think it would be better to move the `fixes` dir into the package instead.
