### ISSUE TITLE
security: customise emails sent by Flask-Security

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#383]
Emails sent by [Flask-Security](https://github.com/Flask-Middleware/flask-security/) currently use the default email templates other than changing the subject via `SECURITY_EMAIL_SUBJECT_REGISTER`.  It would be better to [customise the emails](https://flask-security-too.readthedocs.io/en/stable/customizing.html#emails) for HEPData by overriding these templates.  The same [email_container.html](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/theme/templates/hepdata_theme/email/email_container.html) can be used as for other HEPData emails.  In addition to the content from the [Flask-Security templates](https://github.com/Flask-Middleware/flask-security/tree/master/flask_security/templates/security/email), the custom emails should contain a sentence like:
```html
If you did not request this email from <a href="{{ site_url }}">HEPData.net</a>, please delete this email and <b>do not</b> click on any links.
```
It would be good if the security emails were also sent to the admin email address as for other HEPData emails:

https://github.com/HEPData/hepdata/blob/e47cad458105683a72026fa2dd76c43cbd832aae/hepdata/modules/email/utils.py#L72

This would allow monitoring of new users and manual intervention in the case of suspicious behaviour.  The [Flask-Security docs](https://flask-security-too.readthedocs.io/en/stable/customizing.html#emails) say:

> The default implementation of `MailUtil.send_mail` uses Flask-Mail to create and send the message. By providing your own implementation, you can use any available python email handling package.

So we can perhaps use our own [`send_email`](https://github.com/HEPData/hepdata/blob/e47cad458105683a72026fa2dd76c43cbd832aae/hepdata/modules/email/utils.py#L60-L80) implementation instead of Flask-Mail to send Flask-Security emails.

**Comment by alisonrclarke** [comment]
The Flask-Security package is currently installed in HEPData via invenio-accounts, which does not use the newer [Flask-Security-Too](https://github.com/Flask-Middleware/flask-security) package whose docs you linked, but the no-longer-maintained [Flask-Security](https://github.com/mattupstate/flask-security) package.

So I think for now the best we can do for now is to add custom view templates as per the old [customisation docs](https://flask-security.readthedocs.io/en/stable/customizing.html).

**Comment by GraemeWatt** [comment]
I've opened inveniosoftware/invenio-accounts#375 to upgrade to `Flask-Security-Too`.  In the meantime, I see that the `develop` branch of [Flask-Security](https://github.com/mattupstate/flask-security/tree/develop) has a merged [PR](https://github.com/mattupstate/flask-security/pull/730) to customise `send_mail` (see [docs](https://flask-security.readthedocs.io/en/develop/customizing.html#custom-send-mail-method)), so maybe we could use that by installing `Flask-Security` from GitHub rather than PyPI.

**Comment by alisonrclarke** [comment]
I've managed to customise `send_mail_task` using our current version of flask-security, as well as customising the view templates (all on the [custom-security-emails branch](https://github.com/HEPData/hepdata/tree/custom-security-emails)).
