### ISSUE TITLE
search: enable highlighting of matching search terms

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#39]

**Comment by jstypka** [comment]
The current solution doesn't support uppercase/lowercase differentiation and it breaks links if there is a match inside

**Comment by eamonnmag** [comment]
Darn. Forgot about the links. That can be easily solved however with a
better initial filter on the select call to not replace hrefs. I cast the
net wide initially to avoid having a large loop over all p and h tags for
instance. But in reality this is not so much a problem with the pagination
now in place.

**Comment by eamonnmag** [comment]
The new code now skips anything within a link. Preserving case is still a problem, but I think I have a solution to that.

**Comment by eamonnmag** [comment]
@jstypka we should add in the highlight code directly from ES.

**Comment by jstypka** [comment]
The highlights are already served by ElasticSearch, so now we only need to show them in the frontend. However I'm still not convinced if it would not be better to highlight them directly from JS like it is now

**Comment by eamonnmag** [comment]
Ok, cool. Will have a play and see :)
