### ISSUE TITLE
records: fix extension loading in MathJax

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#395]
Currently we call `MathJax.typeset()` which works synchronously and avoids the need for promises etc, but it doesn't load LaTeX extensions, e.g. `boldsymbol`.

We should switch to using `MathJax.typesetPromise()` to allow extensions to be loaded, but we will need to be careful to handle promises correctly when users switch between tables.

See the [MathJax guide to asynchronous typesetting](http://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting) for details.

**Comment by GraemeWatt** [comment]
An example record is https://www.hepdata.net/record/110989 (in preparation) which contains `$\boldsymbol{ep}$` in the paper title (taken from INSPIRE).  I can reproduce the problem locally after importing the record with the same INSPIRE ID.  The [`\boldsymbol`](http://docs.mathjax.org/en/latest/input/tex/extensions/boldsymbol.html) LaTeX macro requires an extension to be loaded.  An error is then thrown: `Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.parent(e).replaceChild')` which is caught by the `try/catch` introduced in PR #394.  For some unknown reason, the LaTeX encoding is sometimes rendered correctly if the page is refreshed, but this happens much less often on my local instance than on [hepdata.net](https://www.hepdata.net).

**Comment by alisonrclarke** [comment]
@GraemeWatt have you seen the issue with the MathJax working intermittently when refreshing on any other records?

I've got the asynchronous typesetting working locally but I'm still seeing the same issue with that record and am struggling to pin it down. Other records seem to work OK, including with `\boldsymbol` in the title.

**Comment by GraemeWatt** [comment]
I wasn't aware of other records, but searching [hepdata.net](https://www.hepdata.net) for [title:boldsymbol](https://www.hepdata.net/search/?q=title%3Aboldsymbol) there are two finalised records where I see the same problem, i.e. the LaTeX is often not rendered initially, but it sometimes works if I refresh the page.  Similarly for the titles in the search results.  The behaviour varies a bit in Safari, Chrome or Firefox, but in all three browsers I sometimes see problems rendering the LaTeX, just as with https://www.hepdata.net/record/110989 .

**Comment by alisonrclarke** [comment]
If we use the `tex-chtml-full` component rather than `tex-html`, the extensions are loaded with the script rather than being autoloaded. Testing locally it appears that this works consistently for titles with `\boldsymbol` in the title, even with the synchronous MathJax typesetting.

So I'll stick to synchronous but continue with some of the work I've done when trying to fix this, e.g. only typeset newly loaded elements rather than the whole page, and adding try/catch around all calls to ensure that scripts will continue even if MathJax fails, which will hopefully make it more robust.
