### ISSUE TITLE
email: preserve line breaks for Outlook users

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#405]
The email templates contain the CSS property `white-space: pre-wrap` to preserve white space including newline characters that are entered in various text boxes as part of the submission process, such as when creating a new submission or notifying participants.  This is not working for emails sent to my Durham University email address using various email clients (Outlook web app, Outlook for Mac, Outlook for iOS, Apple Mail), so the problem is likely with the email server (Office 365).  Newline characters are correctly preserved for emails sent to my Gmail email address using the Apple Mail client.  To preserve newline characters for Office 365 email, we might need a workaround like replacing newline characters with `<br/>` before messages are passed to the HTML templates.

**Comment by alisonrclarke** [comment]
Could you attach some example emails (including full html) from both your DU and gmail accounts?

**Comment by GraemeWatt** [comment]
I've investigated this problem in more detail in the last couple of days.  If I enter a test review message containing multiple spaces and a line break, it appears correctly when sent to my Gmail email address:
```html
<p style="padding-left: 20px; font-weight: lighter; white-space: pre-wrap;">Test     spacing and

line breaks.</p>
```
But the same test review message sent to my Durham University email address appears as:
```html
<p style=3D"padding-left: 20px; font-weight: lighter; white-space: pre-wrap=
;">Test spacing and line breaks.</p>
```
i.e. the mail server has stripped the extra white space from the email before it arrives at my email client, so `white-space: pre-wrap` cannot preserve the original white space.

I can preserve the line breaks from the Python code before the message is passed to the HTML template using:
```python
from markupsafe import Markup
message=Markup(message.replace('\n', '<br/>'))
```
However, other white space like multiple spaces are not preserved, so the message will still appear differently depending on the mail server.

Alternatively, the message can be wrapped in the HTML template like `<pre>{{ table_message }}</pre>` to preserve white space, but this displays in a fixed-width font.  I guess we could adjust the CSS settings of the `<pre>` tag to give a font similar to the current one.  Could you please look into it, @alisonrclarke?  Or do you have a better idea to solve the problem?

**Comment by alisonrclarke** [comment]
Are we concerned about preserving space at the start of lines (e.g. if people try to indent things as (nested) lists)? If so then `<pre>` tags with amended font might be the best answer - Outlook/O365 seems to preserve line breaks in pre tags. 

If not then replacing newlines with `<br/>` instead of relying on `whitespace:pre-wrap` is probably the safer option as a mail server or client removing line breaks can have no effect then.

**Comment by GraemeWatt** [comment]
Yes, I think it would be better to preserve all whitespace, so better to use `<pre>` tags with an amended font.
