### ISSUE TITLE
records: revise BibTeX format in citation widget

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#408]
The BibTeX format was implemented in https://github.com/HEPData/hepdata/commit/104946f9954cc69c18f6e970ad01da37f7299c6c and mostly unchanged since 2016 apart from the addition of a `url` field requested by @matthewfeickert in https://github.com/HEPData/hepdata/commit/f2d4e0d2dff1a688280dbbb0c21181b0652b87b2.  Here is an example from [a HEPData record](https://www.hepdata.net/record/ins1748602):
```bibtex
@misc {
    1748602,
    title = "{Search for bottom-squark pair production with the ATLAS detector in final states containing Higgs bosons, $b$-jets and missing transverse momentum}",
    abstract = "",
    doi = "10.17182/hepdata.89408.v3",
    url = "https://doi.org/10.17182/hepdata.89408.v3",
    year = "2019",
    type = "Data Collection",
    collaboration = "ATLAS",
    authors = "Aad, Georges and others"
}
```
However, looking at BibTeX documentation (e.g. [Wikipedia](https://en.wikipedia.org/wiki/BibTeX)), the `@misc` type has no required fields, but optional fields are `author` (not `authors`!), `title`, `howpublished`, `month`, `year`, `note`, `key`.  The lack of an `author` field gives a warning message (`Warning--to sort, need author or key in 1748602`) when using the `plain.bst` style file.  Non-standard fields will generally be ignored by BibTeX style files, although some may be supported, for example, [SciPost_bibstyle.bst](https://git.scipost.org/scipost/SciPost_LaTeX_Templates_Submission/-/blob/master/SciPost_bibstyle.bst) used in [arXiv:2109.04981](https://arxiv.org/abs/2109.04981) supports the `doi` field.  To allow the BibTeX format from HEPData to be used with standard BibTeX style files, it would be better to stick to the standard fields, for example:
```bibtex
@misc{hepdata.89408.v3,
    author = "{ATLAS Collaboration}",
    title = "{Search for bottom-squark pair production with the ATLAS detector in final states containing Higgs bosons, $b$-jets and missing transverse momentum}",
    howpublished = "HEPData",
    year = 2019,
    note = "\url{https://doi.org/10.17182/hepdata.89408.v3}"
}
```
@matthewfeickert, after I added the `url` field in 2019, were you able to use the BibTeX format unchanged, or did you first need to modify the BibTeX entry or use a custom style file?  Do you agree with the proposal above to revise the BibTeX format by using standard `@misc` fields?

**Comment by matthewfeickert** [comment]
> after I added the url field in 2019, were you able to use the BibTeX format unchanged, or did you first need to modify the BibTeX entry or use a custom style file?

I unfortunately don't remember the exact project that I was trying to use this in for BibTeX, so I'm really not sure. My guess is that it was either for [use in the `pyhf` docs for published probability models](https://github.com/scikit-hep/pyhf/blob/8a3dc6b489c9a728bbf4994c25a63369100e9c40/docs/bib/HEPData_likelihoods.bib) or for something that would have had a similar use to [this vCHEP 2021 talk proposal](https://github.com/matthewfeickert/pyhf-funcX-CHEP-2021-proposal/blob/536843fe9a7548c4e2b2e440ff0a7558cd1d4f18/bib/ref.bib#L153-L178). In both cases the entries are _slightly_ modified, but not with respect to using the `url` entry &mdash; that all works fine.

> Do you agree with the proposal above to revise the BibTeX format by using standard @misc fields?

I don't think I've ever run into a situation where I've had a `@misc` BibTeX entry fail for having additional information &mdash; I've always just had it not get rendered.

For example, consider the following two source files:

* `main.tex`
```latex
\documentclass{article}

\begin{document}

Hello~\cite{1748602}

\bibliographystyle{plain}
\bibliography{ref}

\end{document}
```
* `ref.bib`
```bibtex
@misc{1748602,
    title = "{Search for bottom-squark pair production with the ATLAS detector in final states containing Higgs bosons, $b$-jets and missing transverse momentum}",
    abstract = "",
    doi = "10.17182/hepdata.89408.v3",
    url = "https://doi.org/10.17182/hepdata.89408.v3",
    year = "2019",
    type = "Data Collection",
    collaboration = "ATLAS",
    authors = "Aad, Georges and others"
}
```

```console
$ tree
.
├── main.tex
└── ref.bib

0 directories, 2 files

```

On my local machine with

```console
$ latex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
```

the command

```console
$ latexmk -pdf -logfilewarnings -halt-on-error main &> latexmk.log.txt
```

produces a PDF without errors containing 

![example](https://user-images.githubusercontent.com/5142394/138400915-a6545972-6794-42b2-bbf2-51ec6263bfc6.png)

and generates the following log file: [latexmk.log.txt](https://github.com/HEPData/hepdata/files/7394632/latexmk.log.txt)


So to my mind there's not a problem here with things as is.

@GraemeWatt I assume that you _have_ come across problem though. Can you share an example?

**Comment by GraemeWatt** [comment]
Thanks, @matthewfeickert, that's very helpful.  Yes, I was using a similar minimal example for testing.  The warning message `Warning--to sort, need author or key in 1748602` is seen on lines 60 and 124 of your `latexmk.log.txt` file.  This is because `plain.bst` sorts references by the `author` (unless there is a `key`).  But the main problem I see is that the reference in the PDF file contains only the paper title and year, which is not very informative, i.e. it does not mention HEPData or give a link to the HEPData record.  These problems are fixed by using the standard `@misc` fields as in my proposal.  Note that I will need to remove the `url` and `doi` fields because otherwise BibTeX style files that support these fields would duplicate the information given in the `note`.

In the [`pyhf` docs](https://scikit-hep.org/pyhf/citations.html#published-statistical-models) I see you're using [sphinxcontrib-bibtex](https://github.com/mcmtroffaes/sphinxcontrib-bibtex), which in turn uses [pybtex](https://pybtex.org), and [unsrt.py](https://bitbucket.org/pybtex-devs/pybtex/src/master/pybtex/style/formatting/unsrt.py) prints both the URL and DOI if given.  This is different from [`unsrt.bst`](http://ftp.cs.stanford.edu/pub/tex/bibtex/unsrt.bst) provided in standard BibTeX where the URL and DOI are not supported.  Your vCHEP 2021 talk proposal uses [woc.bst](https://github.com/matthewfeickert/pyhf-funcX-CHEP-2021-proposal/blob/main/woc.bst) which prints the URL.  So you've maybe not previously encountered problems because you've always used BibTeX style files that support either `url` or `doi` fields in the `@misc` type.  In any case, my proposal of instead giving the URL/DOI in the `note` will work with all BibTeX style files.  For BibTeX style files that do support `url` or `doi` fields, users can replace the `note` with a `url` or `doi` in their own `.bib` files if they prefer, but it should not make much difference to the output.

**Comment by matthewfeickert** [comment]
> In any case, my proposal of instead giving the URL/DOI in the `note` will work with all BibTeX style files.

Seems like that's sufficiently good motivation to use your approach then.

> For BibTeX style files that do support `url` or `doi` fields, users can replace the `note` with a `url` or `doi` in their own `.bib` files if they prefer, but it should not make much difference to the output.

Yeah. I think we have a cultural barrier in HEP that we need to overcome of people wanting a single source of truth (if you will) for BibTeX files from a trusted source to work exactly how they want everywhere. I'm among the guilty here, as it is very nice to have everyone have some canonical source of truth for references (e.g. HEPData, INSPIRE) which don't require any changes, but I suppose that's not really possible.

I think you should move forward with your plans here @GraemeWatt :+1:, but I'll tag a few people that will probably appreciate a heads up on this change: @lukasheinrich, @kratsg, @cranmer, @WolfgangWaltenberger, @sabinekraml.
