### ISSUE TITLE
search: catch exceptions raised by unusual queries

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#427]
Noting a couple of recent search queries that gave rise to Sentry exceptions:

- [x] `] S. Acharya et al. (The ALICE Collaboration), JHEP 11, 013, (2018).` gives "[UndefinedError: 'dict object' has no attribute 'modify_query'](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33498/?query=url%3A%22https%3A%2F%2Fwww.hepdata.net%2Fsearch%2F%22)".  Problem seems to be with the initial `]`.  `cmenergies:[1.3%20TO%201.4]` also gives "[UndefinedError: 'dict object' has no attribute 'modify_query'"](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33498/events/134110/)".  This one comes from a bot and is the same as an example given in "Advanced Search Tips", but with spaces URL-encoded as `%20`.  See also [other Sentry events](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33498/events/) giving rise to the same error.
- [x] `(SELECT (CHR(113)||CHR(122)||CHR(122)||CHR(122)||CHR(113))||(SELECT (CASE WHEN (6242=6242) THEN 1 ELSE 0 END))::text||(CHR(113)||CHR(120)||CHR(107)||CHR(98)||CHR(113)))` gives "[ValueError: too many values to unpack (expected 2)](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/17339/?environment=production)".  Not sure what the intention is here, but it happens sometimes that users try to enter SQL queries, perhaps to test for vulnerabilities.  See also [other Sentry events](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/17339/events/) giving rise to the same error.

The code should be made more robust to catch unusual queries like those examples.

**Comment by alisonrclarke** [comment]
Started work on this on branch `search-exceptions` as I came across the issue when testing OpenDistro in ES. The first issue was cause by an indentation error that must have been introduced at some point.

We should probably add some tests.
