### ISSUE TITLE
records: add last updated date and "Cite" to related_record.html

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#429]
Could the last updated date and the "Cite" button be added to the header of table record pages and resource file landing pages (via `related_record.html`) as they are for publication record pages (`publication_record.html`)?  Ideally, the relevant table or resource file would be selected after clicking the "Cite" button, but this is not essential if it's difficult.  Could you please look into it, @alisonrclarke?

**Comment by GraemeWatt** [comment]
On second thoughts, maybe better if clicking the "Cite" button on a table record page or resource file landing page only gives citation information (with HTML and BibTeX tabs) for that specific item.

**Comment by GraemeWatt** [comment]
Another related suggestion: the version of the record is missing from the table record page or resource file landing page.  It can maybe be included in the header like "gz File from Version 3 of Aad, Georges et al." or "Missing Transverse Energy from Version 3 of Aad, Georges et al." after #428 is fixed.

**Comment by alisonrclarke** [comment]
> On second thoughts, maybe better if clicking the "Cite" button on a table record page or resource file landing page only gives citation information (with HTML and BibTeX tabs) for that specific item.

Should we include the citation info for the full record in addition to the info for the specific table/resource?

**Comment by GraemeWatt** [comment]
> Should we include the citation info for the full record in addition to the info for the specific table/resource?

Yes, that might be a good idea.

**Comment by alisonrclarke** [comment]
I've started implementing this by using a new template for the breadcrumbs and including it in both `publication_record.html` and `related_record.html`. Couple of things we could could include from there in addition:

 * "Accessed X times" info - we only increment counts for publications so I suggest we leave this out for related records
 * "JSON" button - this could return JSON just for the related record (and we could remove the link next to the "copy to clipboard" text

Let me know what you think @GraemeWatt

**Comment by GraemeWatt** [comment]
Yes, that sounds better than duplicating code between the three different templates.  I agree that "Accessed X times" should only be shown for publication records.
