### ISSUE TITLE
records: "string indices must be integers" error

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#432]
The record https://www.hepdata.net/search/?q=inspire_id%3A343229 appears in the search, but https://www.hepdata.net/record/ins343229 gives a [404 error](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33505/?query=is%3Aunresolved) with a message [`string indices must be integers`](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33505/?query=is%3Aunresolved) and https://www.hepdata.net/record/16572 gives a [500 error](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33507/?query=is%3Aunresolved) with `TypeError: string indices must be integers`.  The table record page https://www.hepdata.net/record/16578 displays OK.  This record has updated DOI information on DataCite.  Could you please provide a fix, @alisonrclarke?

**Comment by GraemeWatt** [comment]
I'll add other affected records below as I find them (by looking at Sentry exceptions):
- https://www.hepdata.net/search/?q=inspire_id%3A260834
- https://www.hepdata.net/search/?q=inspire_id%3A500172

**Comment by alisonrclarke** [comment]
Are these all records with 1 table? I think what's happening is the JSON-LD coming from DataCite condenses a `hasPart` list into a single object if there's only 1 child: see https://data.crosscite.org/application/vnd.schemaorg.ld+json/10.17182/hepdata.16572 

I'll add a fix.
