### ISSUE TITLE
records: broken download link on resource file landing page and special treatment needed for .html files

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#438]
Some records migrated from the old HepData site, for example, [ins1208923](https://www.hepdata.net/record/ins1208923) ([old HepData](http://hepdata.cedar.ac.uk/view/ins1208923)) have resources like:

```yaml
additional_resources:
- {description: Rivet analysis, location: 'http://rivet.hepforge.org/analyses#CMS_2013_I1208923'}
- {description: Link to correlation matrices for the Inclusive Jet data, location: /resource/9901922/inclusive_corr.html}
- {description: Link to fastNLO v2.1 table (inclusive jets), location: /resource/1208923/fnl2332d_I1208923.tab.gz}
- {description: Link to correlation matrices for the Dijet data, location: /resource/9901922/dijet_corr.html}
- {description: Link to fastNLO v2.1 table (dijet mass), location: /resource/1208923/fnl2412e_I1208923.tab.gz}
- {description: Link to the detailed systematics for the Inclusive Jet data, location: /resource/9901922/inclusive_sys.html}
- {description: Link to the detailed systematics for the DiJet data, location: /resource/9901922/dijet_sys.html}
```
The resource files are stored in a subdirectory of the main data directory (`/opt/hepdata/var/data/94/66887/resources`).  The last six resources are correctly given a DOI, but the "Download" links are broken from the resource file landing pages, although they work correctly from the "Additional Publication Resources" widget.

Moreover, the landing page for the `.html` files just downloads the `.html` file rather than return the landing page.  Presumably this is because the media type is `text/html`, so we might have to treat this as a special case, e.g. if the media type is `text/html` only return the content directly instead of the landing page if the `flask.request.accept_mimetypes` list has length 1, since [most web browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values) will send an `Accept` header with multiple media types.

Could you please address these issues, @alisonrclarke?

**Comment by alisonrclarke** [comment]
I'm not sure this is just an issue with old records; somehow I'd managed to remove `content_url` from the context at some point. PR on the way.

**Comment by GraemeWatt** [comment]
Yes, it's a general problem, not restricted to records migrated from the old HepData site.
