### ISSUE TITLE
plots: don't visualize records where no data is available

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#44]
e.g. https://hepdata.net/record/ins1387707

**Comment by GraemeWatt** [comment]
For this example, you can still draw the plot axes, but just don't try to plot data points if there aren't any.  Similarly for the case where one or more data points are non-numeric.  Axes ranges could take a default range like 0 to 1, which are overridden only if there is at least one valid data point.  For Table 2 of this example there are no data points, but the values of the independent variable could still define the range of the x axis.  For Table 1, something's also wrong with the display of the table (compare with the information inside the YAML format).  The header for the independent variable is missing and the header for the dependent variable incorrectly appears in the first column (and as the x axis label) where the header for the independent variable should be.
