### ISSUE TITLE
datacite: "Metadata format not recognized" error

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#443]
The first data table "Table of contents" of https://www.hepdata.net/record/ins1750330 has a lot of HTML tags in the description, giving a "DataCiteServerError: Metadata format not recognized" when pushing the XML metadata to DataCite ([Sentry](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/33628/?query=is%3Aunresolved)).  We probably need to sanitise or remove HTML tags from the XML metadata before it is pushed to DataCite.

**Comment by GraemeWatt** [comment]
Something else strange about that [table](https://www.hepdata.net/record/ins1750330?version=1&table=Table%20of%20contents).  The database gives a `DataSubmission` object with `associated_recid=97396` but viewing https://www.hepdata.net/record/97396 gives Table 92 from a different record (https://www.hepdata.net/record/ins147683) which looks the same as https://www.hepdata.net/record/106970.  Not sure how to fix this.

**Comment by alisonrclarke** [comment]
> Something else strange about that [table](https://www.hepdata.net/record/ins1750330?version=1&table=Table%20of%20contents). The database gives a `DataSubmission` object with `associated_recid=97396` but viewing https://www.hepdata.net/record/97396 gives Table 92 from a different record (https://www.hepdata.net/record/ins147683) which looks the same as https://www.hepdata.net/record/106970. Not sure how to fix this.

This looks like an issue with the elasticsearch index. In the DB, the json in `records_metadata` for recid 97396 matches the expected table, but querying elasticsearch for the doc with that id gives Table 92 of the ins147683, but gives QA URLs for downloads. Worth checking we're not doing any indexing on QA? I'll reindex ins1750330 on prod which should fix things.

**Comment by alisonrclarke** [comment]
> This looks like an issue with the elasticsearch index. In the DB, the json in `records_metadata` for recid 97396 matches the expected table, but querying elasticsearch for the doc with that id gives Table 92 of the ins147683, but gives QA URLs for downloads. Worth checking we're not doing any indexing on QA? I'll reindex ins1750330 on prod which should fix things.

Reindexing seems to have worked.
