### ISSUE TITLE
records: improve error message if submission archive extraction fails

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#453]
https://github.com/HEPData/hepdata/blob/710d035c59e4ba75104082af8a6eccef30186bfb/hepdata/modules/records/api.py#L852-L867

Here, the same error message is returned for each of two different cases:

1. `unzipped_path = None` is returned by `extract` because the uploaded file is not a zipfile, a tar file or a gz file.
2. An exception is raised by the `extract` function, generally because of disk access problems.

The latter case is occurring quite frequently in production over the last week or so due to problems accessing the CephFS disk.  However, the current error message is misleading for users (and for me) if there is no problem with the format of the archive file.  A different error message should be given in case 2. including details of the exception (e.g. a problem reading a file from the disk).  The exception should also be logged in Sentry using `log.error` to allow closer monitoring of disk access errors.

**Comment by GraemeWatt** [comment]
On second thoughts, it might be better **not** to catch an exception raised by the `extract` function called from `process_zip_archive`.  Then the exception will instead be caught inside `process_saved_file` allowing Celery to retry the task.  Disk access problems are usually temporary, so retrying has some chance of success.  If not, then the "Unexpected error" message with details of the exception would be included in the error email to the user after the maximum number of Celery retries has been exceeded.

**Comment by GraemeWatt** [comment]
Similarly for the exception raised if a single YAML file cannot be parsed:

https://github.com/HEPData/hepdata/blob/710d035c59e4ba75104082af8a6eccef30186bfb/hepdata/modules/records/utils/yaml_utils.py#L105-L107

If the exception is not caught inside `split_files` it will be caught by `process_saved_file` allowing Celery to retry the task.  I'm seeing a few cases of `[Errno 2] No such file or directory` in error emails and from Sentry after a single YAML file is uploaded.

**Comment by alisonrclarke** [comment]
If we rethrow the exception in `extract` so that celery can retry it, in the case where the file actually is an invalid archive (e.g. a corrupt file, as file extensions are checked on upload), the user will have to wait a while for their failure email and will then see something like this:

![Screenshot 2021-12-09 at 08 07 09](https://user-images.githubusercontent.com/4507639/145358242-1815f238-f2cf-408b-8bbb-b5be2e34b49f.png)

Just checking it's OK to have an 'Unexpected' error in this case?

**Comment by alisonrclarke** [comment]
> Just checking it's OK to have an 'Unexpected' error in this case?

Realised you'd already said an Unexpected Error is OK. Does the user need any further details about the issue? We probably shouldn't give too many details about disk errors to the user, but the original exception will be logged in Sentry so we'd be able to investigate.

**Comment by GraemeWatt** [comment]
If the file is an invalid archive, it won't pass the checks `zipfile.is_zipfile`, `tarfile.is_tarfile` and `is_gz_file` inside `extract`, which will return `None` and the current message `"{} is not a valid zip or tar archive file.".format(file_path)` is fine.  I don't see that an exception will be raised unless there is a disk access problem.  The "Unexpected error" in `process_saved_file` has a message `"An unexpected error occurred: {}".format(e)` which will print details of the exception, so I don't think you need to modify this message.
