### ISSUE TITLE
Make upload parser generate thumbnails for resource figures automatically

### ISSUE THREAD

**Issue by alex-t-grecu** [HEPData/hepdata#459]
Hi,
I acknowledge the nice feature that allows to improve the visual effect (and clarity) of encoded distributions by including also the figure resources associated with the tables. However for early encoders it is sometimes awkward to understand why the thumbnails need to be generated by the encoder and moreover that the name of the thumbnail file must match the name of the high resolution figure modulo the "thumb_" prefix. 
So I'm wondering if it will be such a hassle to modify the upload parser in order to generate automatically the thumbnail file in case it is not included in the upload. Then it would be much easier for encoders to just alter the thumb file in case the automatic resizing does not produce a nice/usable/visible graphic (the upload an improved version of the encoding). I'm aware of the potential security issues in processing the graphic binary files, but in my opinion this should not be such an important issue as most of the times the resource figures come from CDS records for the corresponding published paper.
Alternatively, you should modify the web interface to keep a distinct list of the links to the high resolution figures corresponding to the thumbnails. The present behaviour indicates that the web interface presumes that by removing the "thumb_" prefix, it would get the URL of the high resolution picture and when this is not true the display fails to render the highres figures. Of course this could be solved also by the upload parser enforcing the naming convention for figures and their corresponding thumbnails - at the moment this appears not to be done.
Thanks,
Alex

**Comment by GraemeWatt** [comment]
Many thanks for raising this issue, @alex-t-grecu.  The implementation of thumbnail images using the `thumb_` prefix was carried over from the old HepData site and indeed it is a bit cumbersome.  The feature was originally used for ATLAS and CMS submissions where the analysis pages already contained thumbnail images, so these did not need to be created specifically for the HEPData submission.  However, I would prefer to avoid building in a dependence of the HEPData web application on image processing software to create the thumbnails when processing the upload.

If a HEPData submission is created using the [`hepdata_lib`](https://github.com/hepdata/hepdata_lib) software, there is an option to easily create thumbnail images using the `convert` command of ImageMagick (see "[Adding a plot thumb nail to a table](https://hepdata-lib.readthedocs.io/en/latest/usage.html#adding-a-plot-thumb-nail-to-a-table)" in the `hepdata_lib` docs).  This generally requires the user to have ImageMagick installed on their local machine, although there are [options](https://hepdata-lib.readthedocs.io/en/latest/README.html#getting-started) to run a `hepdata_lib` Docker container (including ImageMagick) either locally or remotely using the [Binder](https://mybinder.org) or [SWAN](https://swan.cern.ch) services.

However, unless the image file is large, it is probably not strictly necessary to create smaller thumbnail images to reduce loading time of the web pages.  Therefore, the user can simply make a copy of the original image file with `thumb_` prepended to the filename, and include both image files as `additional_resources`.  I've used this method for my own submissions ([example](https://github.com/HEPData/hepdata-submission/blob/1d3f760059270e5eeff10b017814a0d90dfe9498/examples/DESY-16-200/process_ins1496981.py#L158-L170)).

We can go a step further and modify the HEPData software to display the original image file if a corresponding thumbnail (with prefix `thumb_`) is not found in the `additional_resources` of a table.  I can then modify the submission documentation to mention that explicitly providing a separate thumbnail image would then be optional and not a requirement.  I've opened a PR #463 with this modification.  Please let us know if this simple modification is sufficient to address your concerns.

**Comment by alex-t-grecu** [comment]
Thank you! Yes the implemented solution is satisfactory as it allows me to avoid confusing encoders without former experience w/ HepData. And we can simply add the thumbnails in case the automatically resize figure is not optimal.
