### ISSUE TITLE
Upgrade Invenio-accounts to v1.4.9 to enable account creation via CLI

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#461]
Attempting to set up HEPData on a new dev machine and the initialise_db script fails to add the user to the DB as it isn't in the request context. v1.4.9 of `invenio-accounts` fixes this (see https://invenio-accounts.readthedocs.io/en/latest/changes.html) but will require upgrades of other Invenio modules including `invenio-base` (which upgrades Flask/Werkzeug to v2 so could require further changes).

**Comment by alisonrclarke** [comment]
I've made a start with minimal dependency updates on the [invenio-updates branch](https://github.com/HEPData/hepdata/tree/invenio-update).

We can stick with Flask v1, but we need to upgrade celery from v44 to v5.1. 

(Note that moving to v5.2 would also mean updating python to > 3.6.)

There is an upgrade guide at https://docs.celeryq.dev/en/v5.1.2/whatsnew-5.1.html#upgrading-from-celery-4-x - referring to the 5 steps there:

1. The branch has changes to the celery command line invocation in the docs, and we will need similar changes to the Kubernetes config. 
2. We can't update the config until [Flask-celeryext issue 44](https://github.com/inveniosoftware/flask-celeryext/issues/44) is fixed.

The remaining steps are OK I think, and the celery tasks seem to work for me locally.

**Comment by GraemeWatt** [comment]
The issue inveniosoftware/flask-celeryext#44 has been closed now and a new version of `Flask-CeleryExt` is available on [PyPI](https://pypi.org/project/Flask-CeleryExt/), but it also drops support for Python 3.6.

**Comment by alisonrclarke** [comment]
Can do this once #467 has been completed.

**Comment by alisonrclarke** [comment]
Have updated Flask-CeleryExt to v0.4.1 on python-updates branch (which now has invenio-updates merged in). There is still one deprecation warning for `BROKER_URL` which looks like a [bug in Flask-CeleryExt](https://github.com/inveniosoftware/flask-celeryext/commit/40fcf75a78c00bbf2aad012f54402e22489642d6#diff-89e59ff28dec12f3435bde8de4898abcf52aeef6d96e2ef5a5c34e6e0df6b68d) - but installing from GitHub didn't fix the issue for me.

Have also pushed kubernetes updates to hepdata-celery-v5 branch.
