### ISSUE TITLE
email: use hepdata.net addresses in "From" header

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#466]
Related to #422, emails sent by the anonymous CERN mail gateway `cernmx.cern.ch` from email addresses other than `*@cern.ch` or `*@hepdata.net` could be marked as spam.  The HEPData submission system mostly sends emails from `submissions@hepdata.net` or `info@hepdata.net`.  However, emails for new Coordinator requests or record questions are sent with the `From` header set to the email address of the HEPData user initiating the request.  I've recently seen a Coordinator request from a `uni-mainz.de` domain end up in my Junk Email folder and labelled as "Unverified".  We should instead send these emails from the `hepdata.net` domain, with the user email instead included as a `Reply-To` header and in the body of the message.  The original use of `Reply-To` was removed five years ago (https://github.com/HEPData/hepdata/commit/bb32d073fa7e7840083992672389f05b76d1a907) as it was not working properly for me, but this should be checked again.

**Comment by alisonrclarke** [comment]
I've just tried setting a reply-to address in Gmail to see how it deals with this: Gmail adds a header 'Reply-To' (note the case, compared to bb32d07), which Outlook respects.

[This StackOverflow answer from 2021](https://stackoverflow.com/questions/32696850/is-the-reply-to-header-universally-supported-among-email-clients/67431324#67431324) also suggests that Reply-To should be respected by most clients.

I guess what we can't be sure of until we try is whether the CERN mail servers will send it as expected.

Perhaps we could also add a line to the relevant emails to try to direct replies to the right place?

**Comment by GraemeWatt** [comment]
I tested your [`email-reply-to`](https://github.com/HEPData/hepdata/tree/email-reply-to) branch locally using [SMTP2GO](https://www.smtp2go.com) to send emails.  In Apple Mail I can see the `Reply-To` in the interface, but it is hidden in Outlook.  In either case, clicking "Reply" starts a reply to the `Reply-To` address as expected.  It still works when changing `Reply-To` to `reply-to` in the Python code.  I don't remember exactly what problems I had in 2016 (probably using Thunderbird as an email client).  But I think we should proceed with setting `Reply-To` in all emails to the address of the user initiating the action.  This email address should also be given in the body of the email, which should already be done in most email templates.

**Comment by alisonrclarke** [comment]
Just checking places where reply_to_address is used:

- `send_question_email`: the reply-to address (user's email) is included in the template
- `send_coordinator_request_mail`: the reply-to address (requester's email) is included in the template
- It's also used when sending emails to the administrator with details of errors moving data files. I'm not sure why I added it in there, but it was for a one-off task anyway so I don't think it needs changing.

**Comment by GraemeWatt** [comment]
Although a `reply_to_address` argument is only used in a couple of places, I think it could be used more widely to set `Reply-To` to the address of the user initiating the action.  For example, in `send_cookie_email` we could pass `reply_to_address=coordinator.email` since invitations are initiated by the Coordinator.  Could you please do this and similar for other relevant email tasks?

**Comment by alisonrclarke** [comment]
Will do. Emails which I don't think need a reply-to address:

- publication_update (done automatically rather than by a user)
- subscriber_notification (we shouldn't be sending coordinator emails to general users)
- upload_complete and upload_errors (the user receiving the notification is the actor)

Does that sound reasonable? I'll add reply-to to the rest.

**Comment by alisonrclarke** [comment]
Actually I could add submission_created to the list because the user receiving the notification is the actor.

**Comment by alisonrclarke** [comment]
submission_status: when it is first sent to a reviewer (including the invitation), should the reply-to address be the coordinator rather than the uploader who has pressed "Notify Participants"? (But use the current user thereafter?)

**Comment by GraemeWatt** [comment]
> Will do. Emails which I don't think need a reply-to address:
> * subscriber_notification (we shouldn't be sending coordinator emails to general users)

This email is intended for general users to get notifications about record revisions if they are subscribed to a particular record.  So maybe a good idea to give the Coordinator email as the reply-to address, since it is the Coordinator who makes the revision public, and the subscribed user might have questions about why the record was revised.

> Actually I could add submission_created to the list because the user receiving the notification is the actor.

Looks like you've added the Coordinator email as the reply-to address, but I agree it's not needed.

> submission_status: when it is first sent to a reviewer (including the invitation), should the reply-to address be the coordinator rather than the uploader who has pressed "Notify Participants"? (But use the current user thereafter?)

I think it's better just to use `reply_to_address = user.email` in all cases, i.e. whoever clicked "Notify Participants".

**Comment by alisonrclarke** [comment]
> > Will do. Emails which I don't think need a reply-to address:
> > 
> > * subscriber_notification (we shouldn't be sending coordinator emails to general users)
> 
> This email is intended for general users to get notifications about record revisions if they are subscribed to a particular record. So maybe a good idea to give the Coordinator email as the reply-to address, since it is the Coordinator who makes the revision public, and the subscribed user might have questions about why the record was revised.

I'd intended to say "shouldn't be sending coordinator *email addresses* to general users" but I now realise they are already on the website anyway. I'll add the reply-to.

> > Actually I could add submission_created to the list because the user receiving the notification is the actor.
> 
> Looks like you've added the Coordinator email as the reply-to address, but I agree it's not needed.
> 
> > submission_status: when it is first sent to a reviewer (including the invitation), should the reply-to address be the coordinator rather than the uploader who has pressed "Notify Participants"? (But use the current user thereafter?)
> 
> I think it's better just to use `reply_to_address = user.email` in all cases, i.e. whoever clicked "Notify Participants".

👍
