### ISSUE TITLE
python: update to python > 3.6

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#467]
python 3.6 reaches end of life in December 2021, so we should upgrade to a newer version. We currently use the [inspirehep python3.6 docker image](https://hub.docker.com/r/inspirehep/python/tags) as a base for the docker image used in production, so we will need to request a new version of that image, which might determine which version we use.

In the meantime we could try out various versions in CI.

**Comment by GraemeWatt** [comment]
There's an image `inspirehep/python:3.8` listed at https://hub.docker.com/r/inspirehep/python/tags that uses Python 3.8.1.  We could check if that image is suitable, although it was last pushed on 25th February 2020 which makes it older than the `inspirehep/python:3.6` image.  We could request a new version from the INSPIRE-HEP team, but it might be more flexible if we used our own base Docker image.

**Comment by alisonrclarke** [comment]
Yes, I meant to mention that. From what I remember the 3.8 image was built from a different base image to the 3.6, but I may be wrong.
