### ISSUE TITLE
dashboard: show more information on submission participants in manager widget

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#469]
Related to this, there is however an interesting feature that could help coordinators, namely, a basic mechanism to inform the coordinator when the persons nominated to different roles regarding an on-going encoding actually interact with the HepData portal based either on the email they receive or simply by accessing the temporary record created for the encoding. This would be of great help in order to understand why for some records there is no progress for a long time and it could help in re-opening discussions about the feasibility of publishing some specific record to HepData (some times proponents are urged to prepare their measurement for HepData, but discover at some point during journal review there is either no time to invest in this action or there are no more available human resources for the task). I think what I propose is to have a limited amount of time (a few months) for an invitation to expire and then have the dashboard pop-up some warning that the record is "forgotten". I could open a different issue on the subject if you consider it worthy of debate.

_Originally posted by @alex-t-grecu in https://github.com/HEPData/hepdata/issues/94#issuecomment-995901343_

**Comment by GraemeWatt** [comment]
The information contained in the `user_account` and `action_date` fields of the `SubmissionParticipant` object could be useful to Coordinators, so we could display it in the manager widget.  The `user_account` is initially null, then is replaced by the ID of the user after they claim permissions, so we could show something like a checkbox "Claimed" to inform the Coordinator whether permissions have been claimed.  The `action_date` is updated when an Uploader makes an upload or when a Reviewer enters a review comment via the `update_action_for_submission_participant` function.  It would be good to also update the `action_date` when the `SubmissionParticipant` object is created, when a participant claims permissions (via the `assign_role` function) and when an Uploader responds to a review comment.  A column like "Last Action" could be added to the manager widget for each primary Uploader and Reviewer with maybe a colour coding based on the date (e.g. green for less than one month ago, yellow for between 1 and 3 months, red for longer than 3 months).  After #191 is addressed, the Coordinator could then choose to resend the invitation email (with optional comments) if there has been no action for several months.

Looking at the code for the manager widget, there is a line:

https://github.com/HEPData/hepdata/blob/384d1f98b169f271d9652619de853c1d8a73964c/hepdata/modules/dashboard/assets/js/hepdata_dashboard_manage_scripts.js#L136

that doesn't seem to do anything apart from print four dashes.  It could be that this line was the start of an uncompleted implementation to show information on "Recent Activity" of participants.  It can be removed if we add "Claimed" and "Last Action" columns for each primary participant.

**Comment by alisonrclarke** [comment]
Could/should the 'last action' column show what the last action is as well as giving the time indication? e.g. 

Uploader:
- unclaimed/not accepted (user account is null)
- claimed/accepted (user account is not null and no data for latest version)
- uploaded (data exists for latest version)

Reviewer:
- awaiting upload (no data for latest version)
- unclaimed/not accepted (user account is null and data exists for latest version)
- claimed/accepted (user account is not null, data exists but no reviews for latest version)
- partially reviewed (some tables have reviews)
- reviewed (all tables have reviews)

**Comment by GraemeWatt** [comment]
We already have information on whether data has been uploaded, how many tables, and the review status of each table in the visualisation on the left-hand side of each entry in the main Dashboard.  So maybe better not to duplicate this information in the manager widget, and just show a "Claimed" checkbox and "Last Action" timestamp.
