### ISSUE TITLE
tests: make test_dashboard more robust

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#484]
Recently the nightly CI tests have been failing (but not every night) with a database connection error when executing the line:

https://github.com/HEPData/hepdata/blob/4af30dbc284353602ac957234982fa31547a1222/tests/e2e/test_dashboard.py#L153-L154

Recent examples: [2nd March](https://github.com/HEPData/hepdata/runs/5385143309?check_suite_focus=true), [27th February](https://github.com/HEPData/hepdata/runs/5347707147?check_suite_focus=true), [26th February](https://github.com/HEPData/hepdata/runs/5341627322?check_suite_focus=true).  Could you please check if the `test_dashboard` end-to-end test could be made more robust, @alisonrclarke?

**Comment by alisonrclarke** [comment]
👍 I'd noticed a few intermittent e2e test failures but hadn't spotted the cause. I'll investigate.

**Comment by GraemeWatt** [comment]
Reopening this issue as the test still failed [last night](https://github.com/HEPData/hepdata/runs/5416543483?check_suite_focus=true) after #486 was merged.
