### ISSUE TITLE
find_element(s)_by_* methods are deprecated in selenium

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata#491]
e.g.

```
tests/e2e/test_dashboard.py::test_dashboard[Chrome]
  /code/tests/e2e/test_dashboard.py:100: DeprecationWarning: find_element_by_link_text is deprecated. Please use find_element(by=By.LINK_TEXT, value=link_text) instead
    browser.find_element_by_link_text('Edit Profile').click()
```

If we continue with selenium (see #487) we should update all the e2e tests to use the `find_element(by=` syntax throughout.

**Comment by GraemeWatt** [comment]
I missed this issue when I opened the duplicate issue #519.  The `find_element(s)_by_*` methods were removed in Selenium v4.3.0 and required a temporary pin before the syntax was updated in PR #521.
