### ISSUE TITLE
theme: improve display of configurable banner

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#496]
A couple of minor issues after issue #322 was addressed via PR #485:

1. When text appears in the banner header, the "HEPData version" text is missing from the footer.
2. HTML links entered via `<a>` tags can be difficult to see (e.g. purple text on a purple background).  It would be better if a style was automatically used for text in `<a>` tags so that it is visible on all web pages.

**Comment by GraemeWatt** [comment]
The "HEPData version" text is missing from the footer even when there is no text in the banner header.

**Comment by alisonrclarke** [comment]
### Explanation of why the HEPData version text is missing

Before #485 was merged, the [homepage template](https://github.com/HEPData/hepdata/blob/5cd319c6b71b845c0d74358d7dc2bb1c6fc9d787/hepdata/modules/theme/templates/hepdata_theme/home.html) overrode most of the [page template](https://github.com/HEPData/hepdata/blob/5cd319c6b71b845c0d74358d7dc2bb1c6fc9d787/hepdata/modules/theme/templates/hepdata_theme/page.html) by overriding `{%- block body %}`. (See [invenio-theme page template](https://github.com/inveniosoftware/invenio-theme/blob/master/invenio_theme/templates/invenio_theme/page.html) for the base template for both.)

I changed that in #485 to override `{% block page_body %}` and use the same headers as the rest of the site so we could configure the banners the same way everywhere.

What I'd missed is that `page.html` uses [`general_footer.html`](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/theme/templates/hepdata_theme/general_footer.html) as its footer content, which removes the version line from [`footer.html`](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/theme/templates/hepdata_theme/footer.html), whereas `home.html` previously used the default footer.html.

To fix it, I think we should remove `general_footer.html` and use `footer.html` throughout, and use a `ctx` variable to determine whether to display the footer. (Unless @GraemeWatt we should just display the version on all pages?)

**Comment by GraemeWatt** [comment]
Thanks for the explanation.  I didn't realise there were two different footers.  Displaying the version on all pages is probably simpler.  I find it handy to check the displayed version has been updated when making a new deployment.

**Comment by alisonrclarke** [comment]
OK, so @zeynepaki I think you just need to remove the file `general_footer.html` and replace references to it with `footer.html`.

**Comment by alisonrclarke** [comment]
We realised that as `version` is only in the jinja context for `home.html` it's simpler to stick to only putting the version on the homepage (but just check whether `ctx` and `ctx.version` are present before displaying it in the footer). Is that OK? (If we really want it to be present on every page we could add a `@app.context_processor` method as we did for `banner_msg`.)

**Comment by GraemeWatt** [comment]
OK, just displaying the version on the homepage is fine.
