### ISSUE TITLE
RFC: watch records for updates

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#51]

**Comment by GraemeWatt** [comment]
Suggested implementation: add a button "Watch this record" for each publication.  When clicked, the email address of the (logged-in) user is added to a list stored for each publication.  This watch list of email addresses is included in the email sent to the Coordinator, Uploader and Reviewer (and copied to info@hepdata.net) when a record is subsequently finalised (and the version number incremented).
