### ISSUE TITLE
RFC: allow users to ask questions about a record 

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#52]
So that people can suggest changes or inform people about mistakes.

**Comment by GraemeWatt** [comment]
Suggested implementation: add a button "Query data submitter" beside each table.  When clicked, it brings up a text box to allow a (logged-in) user to enter a message.  The user clicks "Submit" and their message is sent by email to the registered Coordinator, Uploader and Reviewer (and copied to info@hepdata.net).  Recipients of this email should be hidden from the user.  For submissions made using the old system, the email should instead just be sent to info@hepdata.net.

**Comment by eamonnmag** [comment]
Ah, this is much easier than I initially thought it would be. Ok, sounds good.
