### ISSUE TITLE
Record not loading at all (or loading very slowly)

### ISSUE THREAD

**Issue by kratsg** [HEPData/hepdata#529]
https://www.hepdata.net/record/116034 seems to be taking forever to load. Do you mind taking a look at it?

**Comment by GraemeWatt** [comment]
Thanks for the report.  I'll try to investigate further.  I noticed similar problems with other records in the last day.  In case of a failure, keep reloading the page and it should eventually be successful.  When the page gets stuck on "Loading Data..." there are some errors in the browser console like:
```[Error] Refused to execute https://www.hepdata.net/static/dist/js/manifest.2aacfbd6345e13da36fc.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.```

**Comment by GraemeWatt** [comment]
I think this is a rate-limiting issue which prevents the JavaScript from loading.  I'm not sure why the issue has appeared now, but I fixed it in b453dd6280ddc2d321b2554fa447f726340c66a7 by using the [Flask-Limiter config option](https://flask-limiter.readthedocs.io/en/1.x/#configuration) `RATELIMIT_ENABLED = False`.  Now https://www.hepdata.net/record/116034 loads first time without needing to refresh the page.
