### ISSUE TITLE
plots: deal with % errors

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#54]

**Comment by eamonnmag** [comment]
@GraemeWatt, do you have some examples of this I can use to test? Thanks!

**Comment by GraemeWatt** [comment]
http://hepdata.cedar.ac.uk/view/ins1268975
http://hepdata.cedar.ac.uk/view/ins1306294

**Comment by eamonnmag** [comment]
@GraemeWatt, what is the actual underlying meaning behind all those stat errors - http://hepdata.cedar.ac.uk/view/ins1268975/d1/yaml - is this the sort of one you want summated in to one error bar?

**Comment by GraemeWatt** [comment]
In general, the systematic uncertainty of a measurement is composed of multiple sources.  Often only the total systematic uncertainty is given (or only the "lumi" is separated), but the complete breakdown of sources allows a more rigorous comparison with theoretical predictions accounting for correlations between bins.  Here, it would have been a good idea to give distinct labels to each of the "sys" errors, but still we want to keep them separate.  It is good to allow individual uncertainties to be plotted and we want to keep that feature.  But we also want to allow an option to plot the total uncertainties, calculated by summing in quadrature the individual uncertainties separately in positive and negative directions. i.e. total_plus = sqrt( \sum_{errors} [max(plus, minus, 0)]^2 ) and total_minus = sqrt( \sum_{errors} [min(plus, minus, 0)]^2 ).  Note that we have to be careful for cases like this where the "plus" or "minus" errors can have different signs from usual, i.e. "plus" means moving a given systematic source up by 1-sigma and "minus" means moving the same source down by 1-sigma, which can have an effect on the observable which changes sign along the distribution.  The total uncertainty is also needed for exporting to the YODA format, where multiple uncertainties are not yet supported.

**Comment by eamonnmag** [comment]
@GraemeWatt, favour to ask. This file does not parse due to line 2546 - http://hepdata.cedar.ac.uk/view/ins1306294/yaml. 

The inclusion of 
```yaml
  - {name: $y_{\text{boost}}(Z,b)$, value: '0.0-0.2'}
```
Causes the parser to break. Can you wrap this in quotes? Then it will be fine.

**Comment by eamonnmag** [comment]
Ok, for now, in the display I'll just identify the numerous sys labels with a counter to identify them.
Should have this sorted tomorrow. The display of the labels is a bit messy, need to work out a better way of displaying the errors, but this case is a bit weird. There are so many.

**Comment by GraemeWatt** [comment]
I've now wrapped all qualifier names in quotes.  Do I also need to use quotes for errors given as percentages like `- {symerror: 1.14%, label: 'stat'}` or is this valid YAML?

I think it would be better to only visualise the total uncertainty by default, but allow options for each of the individual uncertainties to be plotted when the user clicks on them.

**Comment by eamonnmag** [comment]
That's valid. But anything that can have yaml reserved  characters needs to
be wrapped as a string. So -  AND {} [] ETC.
