### ISSUE TITLE
werkzeug: Deprecated variable in werkzeug 2.1.* used in SQLAlchemy.

### ISSUE THREAD

**Issue by ItIsJordan** [HEPData/hepdata#540]
Updating werkzeug to v2.1.* removes a deprecated variable **__ident_func__** used by SQLAlchemy which causes an error when attempting to run Hepdata.

**Comment by GraemeWatt** [comment]
The problem might be that `invenio-db` v1.0.13 requires `SQLAlchemy<1.4.0` and installs `SQLAlchemy` v1.3.24.  The solution might be to upgrade to `invenio-db` v1.0.14 which permits the latest `SQLAlchemy` v1.4.42.  If there are errors, a database migration might be needed as explained in [this comment](https://github.com/HEPData/hepdata/issues/539#issuecomment-1293409679).
