### ISSUE TITLE
restful-api: create search and fetch endpoint

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#59]
- [x] Search API endpoint users to search hepdata from other services.
- [x] Fetch API to get records from ES

**Comment by jstypka** [comment]
Do we want to support also some query language e.g.

```
POST /search/api
{
  "query": "higgs boson",
  "filters": [
    {"type": "author", "value": "Maguire, Eamonn"}
  ],
  "size": 20
}
```

or just:
`GET /search/api?query=higgs+boson&size=20` etc.

**Comment by eamonnmag** [comment]
Having support for filters would be great. Something similar to the way
urls are currently created for the front end search would be fine so you
can use exactly the same backend code :)

**Comment by jstypka** [comment]
Yes yes, I'll use the same code - just wondering whether we want to only support GET requests with query parameters or also POST requests with JSON search-DSL body.

**Comment by eamonnmag** [comment]
I generally don't like doing POSTs when they don't change the underlying data. This is one of the criticisms of 'RESTful' - methods that don't do what you expect them to do - http://www.lornajane.net/posts/2013/five-clues-that-your-api-isnt-restful
