### ISSUE TITLE
editing: allow an admin user to edit records within a browser

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#59]
It would be useful to have the facility for an admin user to easily make minor edits to the YAML format of records from a browser (such as correcting typos or modifying/adding keywords) without going through the whole submission system and generating a new version.

Probably only the `submission.yaml` file should be allowed to be easily edited this way.  If changes to data files are required, the normal submission system should be used (generating a new version).

It might be useful to grant "edit" permissions to trusted experts for the `submission.yaml` file of selected records (assigned by an admin user).  Probably "edit" permissions should be granted automatically to the Coordinator/Uploader/Reviewer of a particular record.

**Comment by eamonnmag** [comment]
I think we can do this rather nicely by using the JSON editor and converting to YAML on save. I have a simple version working but requires lots of styling and some extra functionality to hop between records. The advantage of this approach is that the records are always valid. We can then hook up the visualization component to show the rendering as people update.

<img width="1035" alt="screen shot 2016-08-14 at 12 50 42" src="https://cloud.githubusercontent.com/assets/282396/17648661/e2bb130a-621d-11e6-993a-e3ceadf3af43.png">

**Comment by GraemeWatt** [comment]
Request from Frank Geurts (STAR):

> Another feature request, specifically relevant for HEPdata coordinators of larger experiments, is the opportunity to assign -post submission- keywords to the records without having to upload a new version. Keywords become increasingly useful as the HEPdata footprint of my collaboration (RHIC-STAR) continues to increase, and with that, an increase in demand for ways to better parse these data through “advanced” searches. This point was raised today during the STAR Collaboration Meeting.

**Comment by GraemeWatt** [comment]
I'm closing this issue for now, as it's too complicated to implement.  Moreover, in the interests of reproducibility, edits to a record (even just to metadata) should generate a new version and not be done silently.  We don't want to create a disconnect between metadata stored in the database and metadata stored in the original `submission.yaml` file.  This would complicate the situation, for example, if migrating the records to a new system.
