### ISSUE TITLE
search: searching by authors doesn't work

### ISSUE THREAD

**Issue by jstypka** [HEPData/hepdata#61]
Due to the nested mapping of the `authors` field, which is required for aggregation, it has to be searched with a nested query.

http://elasticsearch-users.115913.n3.nabble.com/using-a-nested-object-field-in-a-multi-match-query-td4061613.html
http://stackoverflow.com/questions/31829654/elastic-search-nested-multimatch-query/31829809#31829809

**Comment by eamonnmag** [comment]
What's the status on this @jstypka?

**Comment by jstypka** [comment]
Waiting for a miracle I guess :-) Will try to solve it today or in the following days
