### ISSUE TITLE
admin: overview of all papers submitted using new submission system

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#61]
An admin user should have a dashboard view showing the status of all papers in the submission system, even after finalisation.  (Papers disappear from the current dashboard after finalisation, which limits its usefulness.)  This should show details such as the date of creation, the date each version was finalised, and the names of the Coordinator/Uploader/Reviewer.  It should be possible to filter/search the different fields to get statistics such as the number of papers associated with a particular Coordinator/Uploader/Reviewer.  This overview would be a replacement for the "papers" database on http://hepdata.cedar.ac.uk that has been in use for several years.

**Comment by eamonnmag** [comment]
![submissions-dash](https://cloud.githubusercontent.com/assets/282396/19145593/f36b094c-8baf-11e6-842b-cf2487fd75da.gif)
