### ISSUE TITLE
admin: request and assign Coordinator privileges from web interface

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#63]
After logging in, a normal user should be able to request Coordinator privileges from a web form by filling a (mandatory) text box containing the name of the experiment/group and an (optional) text box with possible extra information.  The contents of the web form should be sent by email to info@hepdata.net.  An admin user should then be able to grant Coordinator privileges from another web interface.

**Comment by GraemeWatt** [comment]
This is great!  Just some minor refinements needed:
- [x] Correct wrong placeholder text in the "Request Coordinator Privileges" box (`Please enter a message detailing what has been changed in this revision.`)
- [x] An email should be sent to the admins (info@hepdata.net) when a coordinator request has been made.
- [x] An email should be sent to the coordinator when their request has been approved (but not if it is rejected).

**Comment by eamonnmag** [comment]
Ok! Will sort this.
