### ISSUE TITLE
records: support positive and negative infinity and “not a number” in YAML format

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#64]
Example: http://hepdata.cedar.ac.uk/view/ins1448101/d4/yaml contains a dependent variable value of 'inf' which the migration code converts to a floating-point `value: .inf` (YAML) or `"value": Infinity` (JSON).  The table cannot be displayed: https://hepdata.net/record/ins1448101?table=Table4

The YAML specification of floating-point numbers (http://yaml.org/type/float.html) includes three special values (positive and negative infinity and “not a number”).  For plotting (and other) purposes, these three special values should be treated in the same way as other non-numeric values.

**Comment by eamonnmag** [comment]
So, this is actually because JSON doesn't support Infinity as a number. But YAML does. I don't know the best way to support this other than converting the infinity and NaNs to a string. Sound ok?
