### ISSUE TITLE
finalisation: error on finalisation from dashboard

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#65]
Error on persistence to elasticsearch to be resolved.

```
RequestError: TransportError(400, u'MapperParsingException[object mapping for [publication] tried to parse field [keywords] as object, but got EOF, has a concrete value been provided to it?]')
```

**Comment by jstypka** [comment]
I think pull request #64 might resolve that (makes keywords an optional field). Can I replicate the error somehow?

**Comment by eamonnmag** [comment]
Yeah, create a submission from the submission form, approve all records, then finalise from the dashboard. I can merge this first, then check again to save you the trouble.

**Comment by jstypka** [comment]
Maybe it would be better to have an obligatory 'keywords' field, however it would just sometimes be empty. We always try to parse keywords from the publication record and return an empty list, so the publication should always have that field anyway.
