### ISSUE TITLE
records: display correct table headers for tables with no data points

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#66]
For example:
  http://hepdata.cedar.ac.uk/view/ins256618/d2
  https://hepdata.net/record/ins256618?table=Table2
should have independent variable header of "DYRAP" and dependent variable header of "D(N)/D(DYRAP)".  The YAML format is migrated correctly, but "DYRAP" is missing from the table display (and the plot) and "D(N)/D(DYRAP)" appears incorrectly over the first column not the second.

A sensible default range (like 0 to 1) should also be chosen for the plot axes, in case there are no numerical data points, rather than numbers like 1e+307 (as at present).

**Comment by eamonnmag** [comment]
It begs the question though, what is the point in these records?

**Comment by GraemeWatt** [comment]
Good question, these records don't have much value.  They are mainly historical records prepared by Russian collaborators.  If the numbers (from plots) weren't available at the time of encoding a record, a table would be prepared with only headers/qualifiers as a placeholder, and the numbers were meant to be filled in later.  This example has a data abstract "DATA REQUESTED 26 APR 1988 BY YGS." but clearly the data points were never obtained.  I suppose the data points could still be filled in using some image recognition software to digitise plots from the journal publication.  However, these old papers are probably not very important nowadays, so this is a minor issue, but probably one that is quite easy to fix.

**Comment by eamonnmag** [comment]
Yup, indeed.
