### ISSUE TITLE
theme: use record-specific `<title>` for record pages

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#689]
Suggestion from @agbuckley:

> I just noticed an awkward aspect of the HepData site when trying to chase back through my browser history in search of a record: the title of every page is just "HEPData", which makes it virtually impossible to know what a given history entry corresponds to.
> 
> Would it be possible to add some record-specific info to the title, e.g. "HEPData -- &lt;experiment&gt;, &lt;year&gt;, &lt;paper title&gt;, &lt;journal ref&gt;"? Doesn't really matter that it's long, if the most important stuff comes first. Thanks for considering: hopefully easy and definitely useful!

The current title "HEPData" seems to come from the [`THEME_SITENAME`](https://github.com/HEPData/hepdata/blob/18881a42b8e4b62e5c6dc20790b3437d3c0c6806/hepdata/config.py#L156) variable, which is set as the `title` by [`invenio-theme`](https://github.com/inveniosoftware/invenio-theme/blob/8cec65fd3692b84c694f3a9ec9cb51c46195c714/invenio_theme/templates/invenio_theme/page.html#L26).  There's some existing code in `publication_record.html` dating from 2015/2016 that tries to include the paper title in the `<title>` tag:
https://github.com/HEPData/hepdata/blob/18881a42b8e4b62e5c6dc20790b3437d3c0c6806/hepdata/modules/records/templates/hepdata_records/publication_record.html#L28-L30

But this doesn't seem to be working.  I think the corrected code would be something like:

```jinja2
 {% block head_title %} 
     <title>HEPData | {{ ctx.record.title }}</title>
 {% endblock %} 
```
There's also some commented-out code that sets the title:
https://github.com/HEPData/hepdata/blob/18881a42b8e4b62e5c6dc20790b3437d3c0c6806/hepdata/modules/records/templates/hepdata_records/publication_record.html#L22-L24

I'm going to use the latter method to set page-specific `<title>` tags for records and other pages.

**Comment by agbuckley** [comment]
Thanks! Just copying in a comment that I made by private email:


It'd be nice if it was easy to include the collaborations (e.g. joined with a ", " or "+" string) if non-null, as I think that's the most distinctive piece of info. It also teds to be short, as is the year, hence my suggestion of putting them at the start so they'll be visible in a cut-off title display, regardless of the title length.  But if getting the collab name(s) is awkward in the templating, then having the title and year is also great: I would just suggest putting them in the opposite order for the reason above. Thanks!
