### ISSUE TITLE
records: allow different formats to be downloaded directly by URL

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#72]
Suppose a user wants to download a particular table from a record defined by an Inspire ID from a script.  At the moment they need to first download the JSON for a whole record (e.g. `https://www.hepdata.net/record/ins1377201?format=json`) to find the URLs of individual tables (defined by the HEPData record ID and table ID).  It would be nice to be able to directly specify URLs like the following:
- `https://www.hepdata.net/record/ins1377201?format=root` (ROOT format for all tables)
- `https://www.hepdata.net/record/ins1377201?table=Table1&format=json` (JSON format for Table 1)
- `https://www.hepdata.net/record/ins1377201?table=Table2&format=yaml&version=1` (YAML format for version 1 of Table 2)

for `format={csv,json,root,yaml,yoda}`.

**Comment by eamonnmag** [comment]
👍

**Comment by eamonnmag** [comment]
You can now download **full submissions** like this:
- **Latest version of Submission ins1283842**
  /download/submission/ins1283842/yaml
- **Version 1 of Submission ins1283842**
  /download/submission/ins1283842/1/yaml

And for **individual data tables**, you can specify:
- **Latest version of Submission ins1283842**
  /download/submission/ins1283842/Table 1/yaml
- **Version 1 of Table 1 Submission ins1283842**
  /download/table/ins1283842/Table 1/1/yaml 
  _or_ /download/table/ins1283842/1/1/yaml

**Comment by GraemeWatt** [comment]
Great, I assume you still need to commit the code for this?
Also, probably you mean /download/**table**/ins1283842/Table 1/yaml?
Since it's better to avoid spaces in URLs, we should also support table names with spaces removed, e.g. `/download/table/ins1283842/Table1/yaml`.

**Comment by GraemeWatt** [comment]
I made some improvements to the download URLs.  Public links should use only the Inspire ID and table name if possible, so that a user does not need to know the HEPData record ID and table ID.  To summarise, here are the main download URL formats currently supported:

- Endpoints for whole submissions are of the form
`/download/submission/ins1283842/1/yaml`
which gives version 1 of submission ins1283842 in a format {json,root,csv,yoda,yaml}.  The HEPData record ID (64673) can be used in place of ins1283842.  Omitting the version number
`/download/submission/ins1283842/yaml`
gives the latest version.  The json format simply gives a redirect, but is included for symmetry with the other formats.

- Endpoints for individual data tables are of the form
`/download/table/ins1283842/Table 1/1/yaml`
which gives version 1 of Table 1 of submission ins1283842 in a format {json,root,csv,yoda,yaml}.  Again, the HEPData record ID (64673) can be used in place of ins1283842, omitting the version number gives the latest version, and the json format simply gives a redirect.  The space in the table name can be omitted for convenience.

- Also support URLs of the form
`/record/ins1283842?table=Table 1&format=yaml&version=1`
which similarly gives version 1 of Table 1 of submission ins1283842 in a format {json,root,csv,yoda,yaml}.  Again, the HEPData record ID (64673) can be used in place of ins1283842, omitting the version number gives the latest version, and the space in the table name can be omitted for convenience.  Formats other than html and json simply redirect to the `/download/` endpoints above.  Omitting the table name gives the whole submission.  An option `light=True` for the json format of a whole submission omits the data tables.
