### ISSUE TITLE
records: clicking "Watch Record" has no effect when not logged in

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#73]
For a user not logged in, clicking the "Watch Record" button has no effect.  It should prompt the user to log in, before adding the record to the watch list of that user.  Alternatively, the "Watch Record" button could simply be hidden if a user is not logged in, but then the existence of the feature is not so visible.

**Comment by eamonnmag** [comment]
Yes, indeed. This just hasn't been tested. Will fix now.
