### ISSUE TITLE
submission: create public web page listing all Coordinators and their experiment/group

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#74]
Often an experimentalist wishing to upload a new HEPData record will not know who to contact to initiate the submission process (i.e. the relevant Coordinator for their experiment/group).  In the old HepData system, we created a simple web page listing the name and email address of all Administrator accounts (http://hepdata.cedar.ac.uk/resource-cgi/writeAdminEmails.pl).  It would be good to have something similar on the new system.  As well as the email address of each Coordinator, it would be useful to list the scope of their responsibilities, e.g. "ATLAS Standard Model group" or "NA61/SHINE experiment", since this information is often not obvious from the email address alone.  The scope would need to be stored as a text field in a database when creating a new Coordinator account, i.e. essentially the contents of

> a (mandatory) text box containing the name of the experiment/group

referred to in #63.

**Comment by eamonnmag** [comment]
Available at /permissions/coordinators

**Comment by GraemeWatt** [comment]
Excellent!  Some minor improvements to be made:
- [x] For a narrow browser window, the name of the experiment/group can overlap with the email address.
- [x] Linking the name of the experiment/group to a search for the `collaboration` won't work in most cases (e.g. the examples I gave like "ATLAS Standard Model group").  Since we know which submissions are associated with a particular coordinator, can't these submissions be displayed when the link is clicked instead of making a search by collaboration?  (If not, I think it would be better just to remove the link.)

**Comment by eamonnmag** [comment]
Oki, thanks!

**Comment by eamonnmag** [comment]
Should be fixed in 4d43316a1679977e4da2920a4fd5473e5366157d
