### ISSUE TITLE
records: display license information if specified

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#740]
The JSON schema defining a HEPData submission has provision for a [`data_licence`](https://github.com/HEPData/hepdata-validator/blob/bfcd4fd2c3bec027816944a60ca92a270e1c356b/hepdata_validator/schemas/1.1.1/submission_schema.json#L31-L37) (comprising a `name`, `url` and optional `description`) for individual tables.  It also supports a [`license`](https://github.com/HEPData/hepdata-validator/blob/bfcd4fd2c3bec027816944a60ca92a270e1c356b/hepdata_validator/schemas/1.1.1/additional_resources_schema.json#L12-L18) for additional resources.  An example of use is given in [`submission.yaml`](https://github.com/HEPData/hepdata-submission/blob/main/examples/submission/TestHEPSubmission/submission.yaml) used in `TestHEPSubmission.zip` and in the [submission documentation](https://hepdata-submission.readthedocs.io/en/latest/submission_yaml.html#full-example).  By default, the [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) license applies, as explained in the [HEPData Terms of Use](https://www.hepdata.net/terms).

The database model defines a [`License`](https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/submission/models.py#L255-L262) object that is used as [`file_license`](https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/submission/models.py#L288-L289) in the `DataResource` object.  The [`data_license`](https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/records/utils/submission.py#L250-L254) and [`license`](https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/records/utils/submission.py#L389-L391) are parsed from the `submission.yaml` file and persisted to the database in `submission.py`.

The license information is written in [`datacite_data_record.xml`](https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_data_record.xml#L47-L51) and in [`datacite_resource.xml`](
https://github.com/HEPData/hepdata/blob/2da796791641f0c0cecc46640a4a615af3531809/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_resource.xml#L42-L46).  However, this information is not rendered on the HEPData web pages.  In view of potential future specification of licence information by the CMS experiment (@clelange), it should be displayed with the data table metadata, on the "Additional Publication Resources" widget and on the resource file landing page.  Only the `name` needs to be displayed, linked to the `url`, with the (optional) `description` given as a tooltip.  To avoid clutter, the default [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) license does not need to be displayed, unless specified explicitly as `data_license` or `license` fields in the `submission.yaml` file.

**Comment by clelange** [comment]
Thanks for following up on this!

CC @lenzip
