### ISSUE TITLE
search: add keyword filtering on records

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata#77]

**Comment by jstypka** [comment]
@eamonnmag, the keywords have a structure of a dict(name=X, value=Y, synonyms=Z), how do we want to create the facet?

Should I aggregate only by value or maybe create another field, say, `full` which would consist of name concatenated with value e.g. "bottom particle : semileptonic decay" and we would aggregate with this field?

**Comment by jstypka** [comment]
Actually, I went with the latter solution and it seems pretty good. The only issue is that the keywords can be pretty long and expand vastly the search box with the coloured tags.

**Comment by eamonnmag** [comment]
Maybe create a facet for each set. There are not so many possibilities and
it would make more sense. So all observables,  reactions etc. Would have
their own group.
