### ISSUE TITLE
Strange rounding in displayed data point values

### ISSUE THREAD

**Issue by alex-t-grecu** [HEPData/hepdata#83]
Dear HepData developers,

The LHCb contributors noticed a strange behaviour of the interface on the new HepData portal. The submitted data values are not affected (I've checked this by exporting the data set in YAML format). But it seems that when the central value in a bin ends in a trailing zero decimal, both the central value and the statistical error are rounded to a smaller number of decimals than the values in the rest of the table. This issue can be seen in http://dx.doi.org/10.17182/hepdata.75193.v1/t1 (see branching fraction value in the first bin) or http://dx.doi.org/10.17182/hepdata.71419.v1/t1 (see value for W minus cross-section in the first bin). I could not see this issue reported and I'm sorry if it is a recurring, known problem that is still pending.

Cheers,
Alex (on behalf of LHCb contributors)

**Comment by eamonnmag** [comment]
Hi @alex-t-grecu, this is caused by a fairly rudimentary check which estimates the number of decimal points to use in a table. Thanks for spotting!
