### ISSUE TITLE
Unregistered DOI

### ISSUE THREAD

**Issue by kaplun** [HEPData/hepdata#89]
If I visit https://hepdata.net/record/ins1509422 and click the DOI, it is actually not registered.

**Comment by kaplun** [comment]
I.e.: 10.17182/hepdata.76719.v1/t1

**Comment by GraemeWatt** [comment]
I just fixed this now by remigrating the record from the old site and registering the DOIs.  I don't know what went wrong originally: the log file gives a `DataCiteBadRequestError` (maybe a missing value in the XML sent to DataCite).  It was a different problem from the 'uuid' and Unicode issues mentioned in #120: there are many reasons why the DOI minting can fail.  Let me know if you find any other records with unregistered DOIs.

**Comment by eamonnmag** [comment]
Yeah, sometimes the service can just go down :( But generally speaking, 25 out of >8500 is not terrible. Thanks for sorting! 💃
