### ISSUE TITLE
dashboard: remove button displaced when the name is too long

### ISSUE THREAD

**Issue by jstypka** [HEPData/hepdata#91]
![screenshot from 2015-09-17 11 51 13](https://cloud.githubusercontent.com/assets/4479536/9930255/abbfff46-5d32-11e5-9a04-a8211ed6e47d.png)

**Comment by eamonnmag** [comment]
Change the text to 'awaiting action' :) Solved.

**Comment by jstypka** [comment]
Haha :smiley:
