### ISSUE TITLE
email: send notification to Coordinator when Reviewer has marked all tables as "Passed"

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata#93]
Currently, there is no automatic way for a Coordinator to know when the Reviewer has marked all tables as "Passed" review and so the record is ready to be finalised.

**Comment by GraemeWatt** [comment]
Or probably better: add a "Notify Coordinator" button to the record when the Reviewer has marked all tables as "Passed" review, similar to the "Notify Reviewer" button that exists for the Uploader.

**Comment by alisonrclarke** [comment]
Do we need a new DB field to keep track of whether the coordinator has been notified? Or should we just allow the reviewer to send multiple notifications?

**Comment by GraemeWatt** [comment]
Changing the DB model to add a new field is more work, so I don't think it's needed, then the Reviewer can send multiple notifications if they want, each with an optional message.
