### ISSUE TITLE
YAML-like error when uploading files with .oldhepdata format

### ISSUE THREAD

**Issue by jmontejo** [HEPData/hepdata#98]
Hi,
I'm trying to upload a file in .oldhepdata format and I get as error:
u'name' is a required property in {}

which looks like it's trying to parse it as YAML.
Do I need anything specific to force it to be read as old hep data?

Regards
Javier

**Comment by eamonnmag** [comment]
Hi Javier, it actually converts your file to YAML behind the scenes then loads it as YAML. So it can be that your original file is missing some required properties. If you post an example, we can find the source of the issue in the original file.

**Comment by GraemeWatt** [comment]
Hi Javier.  Looking at your uploaded files on the disk (for record 77491), I see that your initial attempts only included data tables without any paper metadata.  It looks like you figured out that some initial paper metadata is required just after opening this issue.  This is a limitation that we should fix in the code, i.e. allow upload of .oldhepdata files with only data tables.  For the moment, it's enough just to include a `*comment` entry before the data tables in the .oldhepdata file.

**Comment by jmontejo** [comment]
Hi Eamonn, Graeme,
thanks for the feedback. Indeed that seemed to be the problem. 
It's my first time uploading material and maybe I missed it but I had a hard time finding out which fields were mandatory and which not.
Thanks a lot for the help
